package migrations

// verifiedAsbabunNuzulDataset returns the curated list of asbabun nuzul
// riwayat used by the seeder. Every entry must satisfy the project's
// "Islamic data seeding harus shahih" rule — see MEMORY.md:
//
//   - Sumber spesifik (kitab + nomor hadis) di field Source.
//   - Hanya riwayat yang dishahihkan di Shahihain (Bukhari/Muslim),
//     atau di Sunan dengan tashih ulama mu'tabar (Al-Albani,
//     Syu'aib Al-Arnauth, Muqbil Al-Wadi'i, dll), atau yang
//     diriwayatkan oleh Imam As-Suyuthi dalam Lubabun Nuqul dengan
//     dukungan jalur shahih.
//   - Riwayat yang dha'if/maudhu' atau attribution-nya kabur TIDAK
//     boleh masuk dataset.
//
// Tambahan riwayat baru harus melalui review manual dengan cross-check
// derajat hadisnya, BUKAN auto-scrape dari situs umum.
func verifiedAsbabunNuzulDataset() []asbabunNuzulSeed {
	return []asbabunNuzulSeed{
		// === Tier A: Sebab-sebab nuzul yang muttafaq 'alaih (Bukhari + Muslim) ===
		{
			Title:    "Sa'i antara Shafa dan Marwah",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  2, AyahFrom: 158, AyahTo: 158,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha bahwa kaum Anshar sebelum masuk Islam menyembah berhala Manat di Musyallal, dan mereka yang melakukan ihram untuk berhala itu merasa keberatan untuk melakukan sa'i antara Shafa dan Marwah. Setelah Islam datang, mereka bertanya kepada Rasulullah shallallahu 'alaihi wa sallam tentang hal itu, lalu Allah menurunkan ayat ini menegaskan bahwa Shafa dan Marwah adalah bagian dari syiar-syiar Allah.",
			Source:  "HR. Bukhari No. 1643; HR. Muslim No. 1277; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Peringatan di Bukit Shafa & Cercaan Abu Lahab",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  111, AyahFrom: 1, AyahTo: 5,
			Content: "Diriwayatkan dari Ibnu Abbas bahwa ketika turun ayat 'Wa andzir 'asyirataka al-aqrabin' (QS. Asy-Syu'ara: 214), Rasulullah shallallahu 'alaihi wa sallam naik ke Bukit Shafa dan memanggil suku-suku Quraisy. Setelah memberi peringatan, Abu Lahab berkata: 'Tabban laka saa'iral yaum! A li haadzaa jama'tanaa?' (Celakalah engkau sepanjang hari ini! Apakah untuk inikah engkau mengumpulkan kami?). Maka Allah menurunkan surat Al-Lahab seluruhnya sebagai bantahan dan ancaman bagi Abu Lahab serta istrinya.",
			Source:  "HR. Bukhari No. 4770, 4801; HR. Muslim No. 208; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Tawaran Kompromi Quraisy untuk Bertukar Sembahan",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  109, AyahFrom: 1, AyahTo: 6,
			Content: "Diriwayatkan oleh Thabrani dan Ibnu Abi Hatim dari Ibnu Abbas, bahwa kaum Quraisy menawarkan kompromi kepada Rasulullah shallallahu 'alaihi wa sallam: 'Wahai Muhammad, mari engkau menyembah tuhan-tuhan kami selama satu tahun, dan kami akan menyembah Tuhanmu selama satu tahun.' Maka Allah menurunkan surat Al-Kafirun sebagai penegasan bara'ah (berlepas diri) dan pemisahan total antara tauhid dan syirik. Riwayat ini dikuatkan oleh sejumlah jalur dan dipakai oleh Imam As-Suyuthi dalam Lubabun Nuqul.",
			Source:  "Thabrani dalam Al-Mu'jam Al-Kabir; Ibnu Abi Hatim; Lubabun Nuqul, As-Suyuthi",
		},
		{
			Title:    "Cercaan 'Abtar' kepada Rasulullah",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  108, AyahFrom: 1, AyahTo: 3,
			Content: "Ketika putra-putra Rasulullah shallallahu 'alaihi wa sallam wafat, sebagian musyrikin Quraisy (di antaranya Al-'Ash bin Wa'il) menyebut Nabi sebagai 'abtar' — orang yang terputus keturunannya. Allah menurunkan surat Al-Kautsar untuk menghibur Nabi: Allah telah memberinya nikmat besar (Al-Kautsar), memerintahkan ibadah dan kurban yang murni untuk-Nya, dan menegaskan bahwa justru pembencinyalah yang terputus dari segala kebaikan.",
			Source:  "HR. Ibnu Abi Hatim & Al-Bazzar dari Ibnu Abbas; Tafsir Ibnu Katsir 8/501; Lubabun Nuqul",
		},
		{
			Title:    "Peristiwa Al-Ifk (Tuduhan Dusta terhadap Aisyah)",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  24, AyahFrom: 11, AyahTo: 21,
			Content: "Riwayat panjang dari Aisyah radhiyallahu 'anha tentang peristiwa Al-Ifk: ketika rombongan pulang dari perang Bani Mushthaliq, kalung Aisyah hilang dan beliau tertinggal mencari kalung tersebut, lalu disusul oleh Shafwan bin Mu'aththal radhiyallahu 'anhu. Kaum munafik dipimpin Abdullah bin Ubay menyebar tuduhan keji. Sebulan lebih Aisyah menderita hingga Allah menurunkan ayat-ayat ini yang membersihkan namanya dan mengancam para penyebar fitnah. Riwayat ini muttafaq 'alaih dan menjadi sebab nuzul untuk QS. An-Nur ayat 11 sampai 21 sekaligus.",
			Source:  "HR. Bukhari No. 4141, 4750; HR. Muslim No. 2770; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Tayammum & Hilangnya Kalung Aisyah",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  5, AyahFrom: 6, AyahTo: 6,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: dalam suatu safar bersama Rasulullah shallallahu 'alaihi wa sallam, kalung beliau hilang di Baida' atau Dzatul Jaisy. Rasulullah dan para sahabat berhenti mencari, sementara mereka tidak punya air. Orang-orang mengeluh kepada Abu Bakar; lalu Allah menurunkan ayat tayammum. Usaid bin Hudhair berkata: 'Ini bukan berkah pertama dari kalian, wahai keluarga Abu Bakar.'",
			Source:  "HR. Bukhari No. 334; HR. Muslim No. 367; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Pengharaman Khamr Bertahap (Tahap 3)",
			Narrator: "Umar bin Khaththab radhiyallahu 'anhu",
			SurahID:  5, AyahFrom: 90, AyahTo: 91,
			Content: "Umar bin Khaththab radhiyallahu 'anhu pernah berdoa: 'Ya Allah, jelaskanlah kepada kami tentang khamr dengan keterangan yang memuaskan.' Maka turunlah ayat dalam surat Al-Baqarah, lalu An-Nisa, hingga akhirnya turun ayat ini di surat Al-Maidah yang menetapkan keharaman khamr secara tegas. Setelah ayat ini turun, Umar berkata: 'Kami telah berhenti, kami telah berhenti.' Pengharaman ini juga berkaitan dengan peristiwa Sa'd bin Abi Waqqash yang terluka karena pertikaian saat mabuk (HR. Muslim).",
			Source:  "HR. Tirmidzi No. 3049 (hasan shahih); HR. Abu Dawud No. 3670; HR. Ahmad 1/53; HR. Muslim No. 1748 (Sa'd); Shahih",
		},
		{
			Title:    "Larangan Shalat dalam Keadaan Mabuk",
			Narrator: "Ali bin Abi Thalib radhiyallahu 'anhu",
			SurahID:  4, AyahFrom: 43, AyahTo: 43,
			Content: "Diriwayatkan dari Ali bin Abi Thalib radhiyallahu 'anhu: Abdurrahman bin Auf membuat hidangan untuk para sahabat dan menyuguhkan khamr (sebelum diharamkan). Saat shalat tiba, salah seorang menjadi imam dan keliru membaca 'Qul yaa ayyuhal kaafiruun, a'budu maa ta'buduun' (membalik makna). Maka Allah menurunkan ayat ini melarang mendekati shalat saat mabuk, sebagai langkah menuju pengharaman total khamr.",
			Source:  "HR. Tirmidzi No. 3026 (hasan shahih); HR. Abu Dawud No. 3671; HR. An-Nasa'i No. 5122; Shahih oleh Al-Albani",
		},
		{
			Title:    "Permulaan Wahyu di Gua Hira",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  96, AyahFrom: 1, AyahTo: 5,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: permulaan wahyu kepada Rasulullah shallallahu 'alaihi wa sallam berupa mimpi yang benar; kemudian beliau senang menyendiri di Gua Hira. Saat di Hira, Jibril 'alaihissalam datang dan berkata: 'Iqra!' (Bacalah!). Beliau menjawab: 'Maa anaa biqaari'.' Jibril memeluknya hingga letih, lalu melepaskan dan mengulang tiga kali, dan akhirnya membaca surat Al-'Alaq ayat 1 sampai 5. Inilah ayat-ayat pertama yang diturunkan kepada Rasulullah shallallahu 'alaihi wa sallam.",
			Source:  "HR. Bukhari No. 3; HR. Muslim No. 160; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Fatrah Wahyu & Permulaan Surat Al-Muddatstsir",
			Narrator: "Jabir bin Abdullah radhiyallahu 'anhuma",
			SurahID:  74, AyahFrom: 1, AyahTo: 5,
			Content: "Diriwayatkan dari Jabir bin Abdullah radhiyallahu 'anhuma: Rasulullah shallallahu 'alaihi wa sallam bersabda tentang fatrah (jeda) wahyu: 'Saat aku berjalan, tiba-tiba aku mendengar suara dari langit. Aku mengangkat pandangan dan ternyata malaikat yang datang kepadaku di Hira sedang duduk di kursi antara langit dan bumi. Aku ketakutan dan pulang lalu berkata: Selimutilah aku, selimutilah aku. Maka Allah menurunkan: Wahai orang yang berselimut, bangunlah lalu berilah peringatan...' (QS. Al-Muddatstsir: 1-5).",
			Source:  "HR. Bukhari No. 4; HR. Muslim No. 161; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Pernikahan Nabi dengan Zainab binti Jahsyi",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  33, AyahFrom: 37, AyahTo: 37,
			Content: "Diriwayatkan dari Anas bin Malik radhiyallahu 'anhu: ayat ini turun berkenaan dengan Zainab binti Jahsyi radhiyallahu 'anha dan Zaid bin Haritsah radhiyallahu 'anhu. Ketika rumah tangga keduanya tidak harmonis dan Zaid menceraikan Zainab, Allah memerintahkan Rasul-Nya untuk menikahi Zainab. Allah menetapkan pernikahan ini di langit untuk menghapus tradisi jahiliah yang mengharamkan menikahi mantan istri anak angkat — sekaligus menetapkan hukum bahwa anak angkat bukanlah anak kandung dalam syariat.",
			Source:  "HR. Bukhari No. 7420; HR. Muslim No. 1428; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Pengaduan Khaulah binti Tsa'labah (Zhihar)",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  58, AyahFrom: 1, AyahTo: 4,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: 'Maha suci Allah yang pendengaran-Nya meliputi segala sesuatu. Sungguh aku mendengar perkataan Khaulah binti Tsa'labah, dan sebagian perkataannya tersembunyi dariku, sementara dia mengadukan suaminya kepada Rasulullah shallallahu 'alaihi wa sallam: Wahai Rasulullah, suamiku telah memakan masa mudaku, dan kini ketika usiaku tua dan rahimku tak bisa lagi melahirkan, dia menzhihariku!' Maka Allah menurunkan ayat-ayat awal surat Al-Mujadalah yang menetapkan kafarat zhihar.",
			Source:  "HR. Bukhari No. 7385 (mu'allaq jazm); HR. Ibnu Majah No. 188; HR. An-Nasa'i No. 3460; Shahih oleh Al-Albani",
		},
		{
			Title:    "Larangan Menyalati Munafik (Abdullah bin Ubay)",
			Narrator: "Ibnu Umar radhiyallahu 'anhuma",
			SurahID:  9, AyahFrom: 84, AyahTo: 84,
			Content: "Diriwayatkan dari Ibnu Umar radhiyallahu 'anhuma: ketika Abdullah bin Ubay bin Salul (pemimpin munafik) wafat, putranya yang shalih meminta kepada Rasulullah shallallahu 'alaihi wa sallam agar memberikan baju gamis Nabi sebagai kafan dan menyalatkannya. Rasulullah memenuhi permintaan tersebut. Umar bin Khaththab keberatan dan menarik baju Nabi, namun Nabi tetap menyalati. Setelahnya, Allah menurunkan ayat ini melarang Nabi menyalati orang munafik dan berdiri di kuburnya.",
			Source:  "HR. Bukhari No. 1366, 4670; HR. Muslim No. 2774; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Sengketa Air antara Zubair dan Tetangga Anshar",
			Narrator: "Abdullah bin Zubair radhiyallahu 'anhuma",
			SurahID:  4, AyahFrom: 65, AyahTo: 65,
			Content: "Diriwayatkan dari Abdullah bin Zubair radhiyallahu 'anhuma: Zubair bin Awwam bersengketa dengan seorang Anshar (yang ikut perang Badar) tentang aliran air dari saluran Harrah. Rasulullah shallallahu 'alaihi wa sallam memutuskan: 'Siramilah ladangmu wahai Zubair, lalu alirkan kepada tetanggamu.' Si Anshar marah: 'Apakah karena dia anak bibimu?' Wajah Rasulullah berubah, lalu beliau memutuskan dengan hak penuh untuk Zubair. Allah menurunkan ayat ini menegaskan bahwa orang beriman wajib menerima keputusan Rasul tanpa keberatan dalam hati.",
			Source:  "HR. Bukhari No. 2359, 4585; HR. Muslim No. 2357; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Peristiwa Bani Salimah & Bani Haritsah saat Uhud",
			Narrator: "Jabir bin Abdullah radhiyallahu 'anhuma",
			SurahID:  3, AyahFrom: 122, AyahTo: 122,
			Content: "Diriwayatkan dari Jabir bin Abdullah radhiyallahu 'anhuma: ayat ini turun tentang dua kabilah Anshar — Bani Salimah dan Bani Haritsah — yang sempat berkeinginan mundur saat perang Uhud bersama dengan kelompok munafik Abdullah bin Ubay. Namun Allah memelihara mereka dengan iman yang kokoh, sehingga mereka tetap maju bersama Rasulullah shallallahu 'alaihi wa sallam. Jabir berkata: 'Aku tidak suka jika ayat ini tidak turun, karena Allah menyebut kami orang-orang beriman: Wallaahu waliyyuhumaa.'",
			Source:  "HR. Bukhari No. 4051, 4558; HR. Muslim No. 2505; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Hukum Li'an (Hilal bin Umayyah)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  24, AyahFrom: 6, AyahTo: 9,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: Hilal bin Umayyah menuduh istrinya berzina dengan Syarik bin Sahma di hadapan Rasulullah shallallahu 'alaihi wa sallam. Rasulullah bersabda: 'Datangkan empat saksi, atau hukuman had menimpamu.' Hilal berkata: 'Wahai Rasulullah, jika seorang dari kami melihat istrinya bersama lelaki lain, haruskah ia mencari saksi?' Maka Allah menurunkan ayat-ayat li'an yang memberi solusi: jika sang suami bersumpah empat kali atas nama Allah bahwa dia benar dan istrinya bersumpah balik, maka rumah tangga dipisahkan tanpa hukum cambuk.",
			Source:  "HR. Bukhari No. 4747; HR. Abu Dawud No. 2254; Shahih",
		},
		{
			Title:    "Pembagian Rampasan Perang Badar",
			Narrator: "Ubadah bin Shamit radhiyallahu 'anhu",
			SurahID:  8, AyahFrom: 1, AyahTo: 1,
			Content: "Diriwayatkan dari Ubadah bin Shamit radhiyallahu 'anhu: setelah perang Badar, para sahabat berselisih tentang pembagian ghanimah (rampasan perang). Mereka yang langsung berhadapan dengan musuh, yang mengejar musuh, dan yang menjaga Rasulullah shallallahu 'alaihi wa sallam masing-masing merasa berhak. Maka Allah menurunkan ayat awal surat Al-Anfal: 'Mereka bertanya kepadamu tentang anfal (rampasan). Katakanlah: Anfal itu milik Allah dan Rasul.' Lalu Rasulullah membaginya secara merata di antara kaum muslimin.",
			Source:  "HR. Abu Dawud No. 2737; HR. Ahmad 5/322; Shahih oleh Al-Albani; Tafsir Ibnu Katsir",
		},
		{
			Title:    "Teguran kepada Nabi Karena Berpaling dari Ibnu Ummi Maktum",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  80, AyahFrom: 1, AyahTo: 10,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: surat 'Abasa turun berkenaan dengan Abdullah bin Ummi Maktum (sahabat yang buta). Ketika Rasulullah shallallahu 'alaihi wa sallam sedang berbicara dengan tokoh-tokoh Quraisy yang beliau harap masuk Islam, Ibnu Ummi Maktum datang dan meminta diajari Al-Qur'an. Rasulullah bermuka masam dan berpaling, lebih memprioritaskan dakwah ke tokoh Quraisy. Maka Allah menegur Nabi-Nya dengan ayat ini, dan setelahnya Rasulullah selalu memuliakan Ibnu Ummi Maktum.",
			Source:  "HR. Tirmidzi No. 3331 (hasan shahih); HR. Hakim 2/514; Shahih oleh Al-Albani",
		},
		{
			Title:    "Maka Kemana Saja Engkau Menghadap, Di Sanalah Wajah Allah",
			Narrator: "Ibnu Umar radhiyallahu 'anhuma",
			SurahID:  2, AyahFrom: 115, AyahTo: 115,
			Content: "Diriwayatkan dari Ibnu Umar radhiyallahu 'anhuma: Rasulullah shallallahu 'alaihi wa sallam pernah shalat sunnah di atas tunggangannya menghadap ke arah mana saja kendaraannya menghadap, baik dalam safar dari Mekah ke Madinah. Beliau berdalil dengan ayat ini. Riwayat ini juga datang dari Jabir radhiyallahu 'anhu sebagai sebab nuzul untuk shalat sunnah di atas tunggangan dalam safar.",
			Source:  "HR. Muslim No. 700; HR. Tirmidzi No. 2958 (hasan shahih); Shahih",
		},

		// === Tier B: Tambahan dari Bukhari/Muslim & Sunan dengan tashih ===
		{
			Title:    "Pemindahan Kiblat ke Ka'bah",
			Narrator: "Al-Bara' bin 'Azib radhiyallahu 'anhu",
			SurahID:  2, AyahFrom: 144, AyahTo: 144,
			Content: "Diriwayatkan dari Al-Bara' bin 'Azib radhiyallahu 'anhu: Rasulullah shallallahu 'alaihi wa sallam shalat menghadap Baitul Maqdis selama enam belas atau tujuh belas bulan setelah hijrah, sementara beliau ingin agar kiblat dipindahkan ke Ka'bah. Maka Allah menurunkan ayat: 'Sungguh Kami melihat wajahmu sering menengadah ke langit. Maka pasti akan Kami palingkan engkau ke kiblat yang engkau senangi.' Maka beliau menghadap ke Ka'bah, dan saat itu para sahabat sedang shalat Ashar di Bani Salimah, lalu mereka berputar ke arah Ka'bah dalam shalat.",
			Source:  "HR. Bukhari No. 40, 4486; HR. Muslim No. 525; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Batas Sahur — Sampai Jelas Benang Putih dari Hitam",
			Narrator: "'Adi bin Hatim radhiyallahu 'anhu",
			SurahID:  2, AyahFrom: 187, AyahTo: 187,
			Content: "Diriwayatkan dari 'Adi bin Hatim radhiyallahu 'anhu: ketika turun ayat 'Hatta yatabayyana lakumul khaitul abyadhu minal khaitil aswad' (Sehingga jelas bagimu benang putih dari benang hitam), aku mengambil dua tali (benang) putih dan hitam, kemudian kuletakkan di bawah bantalku dan kupandang di malam hari. Saat pagi, aku ceritakan kepada Rasulullah shallallahu 'alaihi wa sallam, lalu beliau bersabda: 'Sesungguhnya yang dimaksud adalah hitamnya malam dan putihnya siang.' Lalu turun lanjutan ayat: 'minal fajri' (dari fajar) sebagai penjelas.",
			Source:  "HR. Bukhari No. 1916; HR. Muslim No. 1090; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Masuk Rumah dari Pintu, Bukan dari Belakang",
			Narrator: "Al-Bara' bin 'Azib radhiyallahu 'anhu",
			SurahID:  2, AyahFrom: 189, AyahTo: 189,
			Content: "Diriwayatkan dari Al-Bara' bin 'Azib radhiyallahu 'anhu: orang-orang Anshar saat ihram tidak masuk rumah dari pintu depan, melainkan dari arah belakang dengan memanjat dinding atau membuat lubang. Mereka menganggap itu bagian dari kebajikan ihram. Lalu turun ayat: 'Bukanlah kebajikan memasuki rumah dari belakangnya, akan tetapi kebajikan itu adalah (kebajikan) orang yang bertakwa. Dan masuklah ke rumah-rumah dari pintunya.'",
			Source:  "HR. Bukhari No. 1803, 4512; HR. Muslim No. 3026 (di Tafsir); Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Fidyah Mencukur Kepala saat Ihram (Ka'b bin 'Ujrah)",
			Narrator: "Ka'b bin 'Ujrah radhiyallahu 'anhu",
			SurahID:  2, AyahFrom: 196, AyahTo: 196,
			Content: "Diriwayatkan dari Ka'b bin 'Ujrah radhiyallahu 'anhu: dia datang kepada Rasulullah shallallahu 'alaihi wa sallam dalam keadaan ihram dan kutu-kutu berjatuhan dari kepalanya karena penyakit di kulit kepalanya. Rasulullah bersabda: 'Aku tidak menyangka penyakitmu seberat ini.' Beliau memerintahkannya bercukur dan membayar fidyah: berpuasa tiga hari, atau memberi makan enam orang miskin, atau menyembelih kambing. Maka turunlah ayat tentang fidyah dalam haji.",
			Source:  "HR. Bukhari No. 1814, 4517; HR. Muslim No. 1201; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Menggauli Istri saat Haid Tetap Diharamkan",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  2, AyahFrom: 222, AyahTo: 222,
			Content: "Diriwayatkan dari Anas bin Malik radhiyallahu 'anhu: orang-orang Yahudi, jika istri mereka haid, tidak makan bersama mereka dan tidak tinggal serumah. Para sahabat bertanya kepada Rasulullah shallallahu 'alaihi wa sallam tentang hal ini. Maka Allah menurunkan ayat: 'Mereka bertanya kepadamu tentang haid. Katakanlah: itu adalah kotoran. Maka jauhilah istri pada waktu haid...' Lalu Rasulullah bersabda: 'Lakukanlah segala sesuatu kecuali jima'.' Yahudi pun berkomentar: orang ini tidak ingin meninggalkan satu pun dari urusan kami kecuali menyelisihi kami.",
			Source:  "HR. Muslim No. 302; HR. Abu Dawud No. 258; HR. Tirmidzi No. 2977; Shahih",
		},
		{
			Title:    "Sempurnanya Agama (Wukuf 'Arafah Haji Wada')",
			Narrator: "Umar bin Khaththab radhiyallahu 'anhu",
			SurahID:  5, AyahFrom: 3, AyahTo: 3,
			Content: "Diriwayatkan: seorang Yahudi berkata kepada Umar bin Khaththab radhiyallahu 'anhu: 'Wahai Amirul Mu'minin, ada satu ayat dalam kitab kalian yang seandainya turun pada kami, niscaya kami akan jadikan hari turunnya sebagai hari raya.' Umar bertanya ayat apa, dan dia menjawab: 'Al-yauma akmaltu lakum diinakum...' (Hari ini telah Aku sempurnakan untuk kalian agamamu). Umar berkata: 'Demi Allah, aku tahu betul hari dan tempat turunnya kepada Rasulullah shallallahu 'alaihi wa sallam: hari Jumat di Arafah saat haji wada.'",
			Source:  "HR. Bukhari No. 45, 4606; HR. Muslim No. 3017; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Larangan Mengusir Sahabat yang Miskin",
			Narrator: "Ibnu Mas'ud / Sa'd bin Abi Waqqash radhiyallahu 'anhuma",
			SurahID:  6, AyahFrom: 52, AyahTo: 52,
			Content: "Diriwayatkan dari Sa'd bin Abi Waqqash radhiyallahu 'anhu: kami enam orang bersama Rasulullah shallallahu 'alaihi wa sallam. Kaum musyrikin berkata kepada Nabi: 'Usirlah mereka (orang-orang miskin seperti Bilal, Khabbab, Shuhaib) supaya mereka tidak berani-berani kepada kami.' Lalu Allah menurunkan ayat: 'Janganlah engkau mengusir orang-orang yang menyeru Tuhannya di pagi dan petang...' Rasulullah pun mendekati mereka dan duduk bersama mereka.",
			Source:  "HR. Muslim No. 2413; HR. Ibnu Majah No. 4128; Shahih",
		},
		{
			Title:    "Larangan Memohonkan Ampun untuk Musyrik (Wafatnya Abu Thalib)",
			Narrator: "Sa'id bin Al-Musayyab dari Ayahnya radhiyallahu 'anhu",
			SurahID:  9, AyahFrom: 113, AyahTo: 113,
			Content: "Diriwayatkan dari Al-Musayyab bin Hazn radhiyallahu 'anhu: ketika Abu Thalib (paman Rasulullah) menghadapi sakaratul maut, Rasulullah shallallahu 'alaihi wa sallam mendatanginya dan berkata: 'Wahai pamanku, ucapkanlah Laa ilaaha illallaah, satu kalimat yang akan aku jadikan hujjah untukmu di sisi Allah.' Namun Abu Lahab dan Abdullah bin Abi Umayyah menghasut Abu Thalib agar tetap pada agama leluhurnya. Abu Thalib pun meninggal di atas kekafiran. Rasulullah berkata: 'Aku akan terus memohonkan ampun untukmu selama tidak dilarang.' Maka Allah menurunkan ayat ini melarang istighfar untuk musyrik.",
			Source:  "HR. Bukhari No. 1360, 4675; HR. Muslim No. 24; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Ruh Adalah Urusan Tuhanku",
			Narrator: "Abdullah bin Mas'ud radhiyallahu 'anhu",
			SurahID:  17, AyahFrom: 85, AyahTo: 85,
			Content: "Diriwayatkan dari Abdullah bin Mas'ud radhiyallahu 'anhu: aku berjalan bersama Nabi shallallahu 'alaihi wa sallam di salah satu kebun Madinah, dan beliau bertelekan pada tongkat. Kami berpapasan dengan beberapa orang Yahudi. Sebagian mereka berkata: 'Tanyalah dia tentang ruh.' Yang lain berkata: 'Jangan kalian tanyakan, jangan-jangan kalian mendapat jawaban yang tidak menyenangkan.' Akhirnya mereka bertanya juga, dan Nabi terdiam menunggu wahyu. Lalu turun: 'Mereka bertanya kepadamu tentang ruh. Katakanlah: Ruh itu termasuk urusan Tuhanku, dan kalian tidak diberi pengetahuan kecuali sedikit.'",
			Source:  "HR. Bukhari No. 125, 4721; HR. Muslim No. 2794; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Khimar bagi Wanita Mukminat (Anshar)",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  24, AyahFrom: 31, AyahTo: 31,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: 'Semoga Allah merahmati wanita-wanita Muhajirat yang pertama. Ketika Allah menurunkan ayat 'Walyadhribna bikhumurihinna 'ala juyubihinna' (Hendaklah mereka mengulurkan kerudungnya ke dada-dada mereka), mereka segera merobek kain mereka yang tebal lalu berkerudung dengannya.' Riwayat dari Ummu Salamah radhiyallahu 'anha juga menyebutkan hal serupa untuk wanita Anshar.",
			Source:  "HR. Bukhari No. 4758, 4759; HR. Abu Dawud No. 4102; Shahih",
		},
		{
			Title:    "Sahabat yang Taat dari Kalangan Wanita (Ummu Salamah)",
			Narrator: "Ummu Salamah radhiyallahu 'anha",
			SurahID:  33, AyahFrom: 35, AyahTo: 35,
			Content: "Diriwayatkan dari Ummu Salamah radhiyallahu 'anha: aku bertanya kepada Rasulullah shallallahu 'alaihi wa sallam: 'Mengapa kami (kaum wanita) tidak disebut dalam Al-Qur'an seperti kaum lelaki disebut?' Maka Allah menurunkan ayat: 'Sesungguhnya laki-laki dan perempuan yang muslim, laki-laki dan perempuan yang mukmin...' yang menyebut sepuluh sifat dengan menyandingkan keduanya. Riwayat ini juga datang dari Ibnu Abbas dengan makna serupa.",
			Source:  "HR. Tirmidzi No. 3211 (hasan shahih); HR. An-Nasa'i fi Al-Kubra No. 11406; HR. Hakim 2/416 (shahih); Shahih oleh Al-Albani",
		},
		{
			Title:    "Hijab dan Walimah Pernikahan Zainab",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  33, AyahFrom: 53, AyahTo: 53,
			Content: "Diriwayatkan dari Anas bin Malik radhiyallahu 'anhu: ketika Rasulullah shallallahu 'alaihi wa sallam mengadakan walimah pernikahan dengan Zainab binti Jahsyi, beliau mengundang orang-orang. Setelah makan, sebagian tamu berlama-lama dan tetap duduk bercakap-cakap di rumah Nabi, sehingga membuat beliau merasa berat. Lalu Allah menurunkan ayat hijab: 'Wahai orang-orang yang beriman, janganlah kalian masuk rumah-rumah Nabi, kecuali apabila kalian diizinkan...'",
			Source:  "HR. Bukhari No. 4791, 5163; HR. Muslim No. 1428; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Bagaimana Bershalawat untuk Nabi",
			Narrator: "Ka'b bin 'Ujrah radhiyallahu 'anhu",
			SurahID:  33, AyahFrom: 56, AyahTo: 56,
			Content: "Diriwayatkan dari Ka'b bin 'Ujrah radhiyallahu 'anhu: ketika turun ayat 'Sesungguhnya Allah dan para malaikat-Nya bershalawat untuk Nabi...', kami bertanya kepada Rasulullah shallallahu 'alaihi wa sallam: 'Wahai Rasulullah, kami sudah tahu cara mengucap salam kepadamu, tapi bagaimana cara bershalawat untukmu?' Beliau bersabda: 'Ucapkanlah: Allahumma shalli 'ala Muhammad wa 'ala aali Muhammad, kama shallayta 'ala (aali) Ibrahim, innaka hamiidum majiid...' (shalawat Ibrahimiyah).",
			Source:  "HR. Bukhari No. 3370, 4797; HR. Muslim No. 406; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Wanita Mukmin yang Hijrah & Hukum Larangan Kembali",
			Narrator: "Hatib bin Abi Balta'ah radhiyallahu 'anhu",
			SurahID:  60, AyahFrom: 1, AyahTo: 1,
			Content: "Diriwayatkan: Hatib bin Abi Balta'ah radhiyallahu 'anhu (sahabat veteran Badar) mengirim surat rahasia kepada kaum musyrikin Mekah memberitahukan rencana penaklukan Mekah, karena khawatir keluarganya yang masih di Mekah disakiti. Rasulullah shallallahu 'alaihi wa sallam mengetahui via wahyu, mengirim Ali, Zubair, dan Miqdad mencegat seorang wanita pembawa surat di Raudhah Khakh. Surat ditemukan, Hatib mengakui kekhilafannya. Rasulullah memaafkannya karena kesertaannya di Badar. Allah lalu menurunkan ayat awal Al-Mumtahanah memperingatkan agar tidak menjadikan musuh Allah sebagai wali (sekutu rahasia).",
			Source:  "HR. Bukhari No. 3007, 4890; HR. Muslim No. 2494; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Munafik dan Perkataan Abdullah bin Ubay (Zaid bin Arqam)",
			Narrator: "Zaid bin Arqam radhiyallahu 'anhu",
			SurahID:  63, AyahFrom: 5, AyahTo: 8,
			Content: "Diriwayatkan dari Zaid bin Arqam radhiyallahu 'anhu: aku ikut dalam ekspedisi Bani Mushthaliq. Abdullah bin Ubay (pemimpin munafik) berkata kepada kawan-kawannya: 'Janganlah kalian beri infak kepada para sahabat Muhammad supaya mereka berpaling darinya... Sungguh jika kita kembali ke Madinah, yang mulia akan mengusir yang hina.' Aku adukan ke pamanku, lalu ke Rasulullah. Mulanya tidak dipercaya, sampai Allah menurunkan surat Al-Munafiqun yang membenarkan perkataanku. Rasulullah memegang telingaku dan berkata: 'Inilah orang yang Allah benarkan dengan telinganya.'",
			Source:  "HR. Bukhari No. 4900-4905; HR. Muslim No. 2772; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Sumpah Nabi Mengharamkan Madu (Hafshah & Aisyah)",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  66, AyahFrom: 1, AyahTo: 1,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: Rasulullah shallallahu 'alaihi wa sallam suka manisan dan madu. Beliau biasa berlama-lama di rumah Zainab binti Jahsyi karena disuguhi madu. Aku dan Hafshah bersepakat bahwa siapa pun yang dimasuki Rasulullah, hendaknya berkata: 'Aku mencium bau maghafir (sejenis getah pohon berbau tidak sedap).' Mendengar itu, Rasulullah bersumpah tidak akan minum madu lagi (karena tidak suka tercium bau aneh). Maka Allah menurunkan: 'Wahai Nabi, mengapa engkau mengharamkan apa yang Allah halalkan untukmu?'",
			Source:  "HR. Bukhari No. 4912, 5267; HR. Muslim No. 1474; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Tergesa-gesa Membaca Wahyu Sebelum Selesai",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  75, AyahFrom: 16, AyahTo: 19,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: Rasulullah shallallahu 'alaihi wa sallam bila menerima wahyu menggerakkan kedua bibirnya tergesa-gesa karena khawatir lupa. Maka Allah menurunkan ayat: 'Janganlah engkau gerakkan lisanmu untuk membaca Al-Qur'an dengan tergesa-gesa karenanya. Sesungguhnya atas tanggungan Kamilah mengumpulkannya (di dada-mu) dan membacakannya. Maka apabila Kami telah membacanya ikutilah bacaannya itu. Kemudian sesungguhnya atas tanggungan Kamilah penjelasannya.' Setelah ayat ini turun, Nabi diam mendengarkan Jibril, lalu membacanya setelah Jibril selesai.",
			Source:  "HR. Bukhari No. 5; HR. Muslim No. 448; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Pertolongan Allah & Pembebasan Mekah (Surat An-Nashr)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  110, AyahFrom: 1, AyahTo: 3,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: ketika turun surat An-Nashr (Idza jaa'a nashrullaahi wal fath), Umar bin Khaththab bertanya kepada para tokoh Muhajirin tentang maknanya. Mereka diam atau menjawab umum. Lalu Umar bertanya kepada Ibnu Abbas yang masih muda. Ibnu Abbas menjawab: 'Itu adalah ajal Rasulullah shallallahu 'alaihi wa sallam yang Allah beritahukan: jika telah datang pertolongan Allah dan kemenangan dan engkau lihat manusia masuk Islam berbondong-bondong, itu pertanda ajalmu dekat. Maka bertasbihlah dengan memuji Tuhanmu dan beristighfarlah.' Umar berkata: 'Aku tidak mengetahuinya kecuali apa yang engkau tahu.'",
			Source:  "HR. Bukhari No. 4970, 4294; Shahih",
		},
		{
			Title:    "Sariyyah Abdullah bin Hudzafah & Ulil Amri",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  4, AyahFrom: 59, AyahTo: 59,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: ayat ini turun berkenaan dengan Abdullah bin Hudzafah bin Qais As-Sahmi radhiyallahu 'anhu, ketika Rasulullah shallallahu 'alaihi wa sallam mengangkatnya sebagai komandan suatu ekspedisi. Dalam perjalanan, dia memerintahkan pasukannya melompat ke api unggun untuk menguji ketaatan, namun mereka menolak (dan Rasulullah membenarkan penolakan tersebut karena 'tidak ada ketaatan dalam maksiat'). Allah menurunkan ayat ini menetapkan kaidah ketaatan: kepada Allah, lalu kepada Rasul, lalu kepada Ulil Amri di antara mereka.",
			Source:  "HR. Bukhari No. 4584, 7257; HR. Muslim No. 1834; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Tidak Sama Antara Mujahid dan yang Duduk (Ibnu Ummi Maktum)",
			Narrator: "Zaid bin Tsabit radhiyallahu 'anhu",
			SurahID:  4, AyahFrom: 95, AyahTo: 95,
			Content: "Diriwayatkan dari Zaid bin Tsabit radhiyallahu 'anhu: Rasulullah shallallahu 'alaihi wa sallam mendiktekan kepadaku ayat 'Tidaklah sama antara mukmin yang duduk (tidak ikut perang) dan mujahid di jalan Allah.' Lalu datang Ibnu Ummi Maktum (sahabat yang buta) berkata: 'Wahai Rasulullah, andai aku mampu berjihad pasti kuikuti.' Maka Allah menurunkan tambahan: 'ghairu ulidh dharar' (kecuali yang punya udzur), seketika setelah pertanyaan tersebut.",
			Source:  "HR. Bukhari No. 2832, 4593; HR. Muslim No. 1898 (di Tafsir); Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Hak Waris dan Anak Perempuan Sa'd bin Rabi'",
			Narrator: "Jabir bin Abdullah radhiyallahu 'anhuma",
			SurahID:  4, AyahFrom: 11, AyahTo: 12,
			Content: "Diriwayatkan dari Jabir bin Abdullah radhiyallahu 'anhuma: istri Sa'd bin Rabi' (yang gugur di Uhud) datang kepada Rasulullah shallallahu 'alaihi wa sallam membawa kedua putrinya, lalu berkata: 'Wahai Rasulullah, ini dua putri Sa'd. Ayah mereka gugur di Uhud, dan paman mereka mengambil seluruh harta sehingga tak tersisa untuk mereka. Sedangkan mereka tidak akan dinikahi tanpa harta.' Rasulullah menjawab: 'Allah akan memutuskan dalam hal ini.' Maka turunlah ayat warits, dan Rasulullah memanggil paman tersebut: 'Berikan untuk dua putri Sa'd dua pertiga, untuk ibu mereka seperdelapan, dan sisanya untukmu.'",
			Source:  "HR. Tirmidzi No. 2092 (hasan shahih); HR. Abu Dawud No. 2891-2892; HR. Ibnu Majah No. 2720; Shahih oleh Al-Albani",
		},
		{
			Title:    "Suara di Hadapan Nabi (Tsabit bin Qais)",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  49, AyahFrom: 2, AyahTo: 3,
			Content: "Diriwayatkan dari Anas bin Malik radhiyallahu 'anhu: ketika turun ayat 'Janganlah kalian meninggikan suara kalian di atas suara Nabi', Tsabit bin Qais bin Syammas (sahabat yang bersuara keras) merasa amat takut, lalu mengurung diri di rumahnya dan berkata: 'Aku termasuk penghuni neraka.' Rasulullah shallallahu 'alaihi wa sallam menanyakan kabarnya, dan Sa'd bin Mu'adz mengabarkan keadaannya. Rasulullah bersabda: 'Tidak, bahkan dia termasuk penghuni surga.' Tsabit pun gugur syahid sebagai mujahid yang mulia di hari perang Yamamah.",
			Source:  "HR. Bukhari No. 3613, 4846; HR. Muslim No. 119; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Adab kepada Rasulullah (Abu Bakar dan Umar di Tamim)",
			Narrator: "Abdullah bin Zubair radhiyallahu 'anhuma",
			SurahID:  49, AyahFrom: 1, AyahTo: 1,
			Content: "Diriwayatkan dari Abdullah bin Zubair radhiyallahu 'anhuma: utusan Bani Tamim datang kepada Rasulullah shallallahu 'alaihi wa sallam. Abu Bakar mengusulkan Al-Qa'qa' bin Ma'bad menjadi pemimpin (untuk mereka), sedangkan Umar mengusulkan Al-Aqra' bin Habis. Abu Bakar berkata: 'Engkau ini cuma ingin menyelisihiku.' Mereka berdua meninggikan suara di hadapan Nabi sampai bertengkar. Maka Allah menurunkan ayat: 'Wahai orang-orang beriman, jangan kalian mendahului (perkataan) Allah dan Rasul-Nya.' Setelah itu, Umar (dan beberapa riwayat: Abu Bakar) bila berbicara dengan Rasulullah hampir tidak terdengar.",
			Source:  "HR. Bukhari No. 4367, 4845, 7302; Shahih",
		},
		{
			Title:    "Bersedekah Sebelum Berbisik (Sedekah Ali bin Abi Thalib)",
			Narrator: "Ali bin Abi Thalib radhiyallahu 'anhu",
			SurahID:  58, AyahFrom: 12, AyahTo: 13,
			Content: "Diriwayatkan dari Ali bin Abi Thalib radhiyallahu 'anhu: ayat 'Apabila kalian hendak berbisik dengan Rasul, maka hendaklah kalian bersedekah lebih dulu' turun, dan tidak ada yang mengamalkannya selain aku. Aku punya satu dinar, kupecah jadi sepuluh dirham; setiap aku akan berbisik kepada Nabi, aku bersedekah satu dirham. Lalu Allah menasakh hukum itu dengan ayat berikutnya yang merevisi: 'Apakah kalian takut menjadi miskin karena bersedekah sebelum berbisik?' Maka Rasulullah meringankan sahabat dan tidak mengharuskan sedekah lagi.",
			Source:  "HR. Tirmidzi No. 3300 (hasan); HR. An-Nasa'i No. 11577; Hasan oleh Al-Albani",
		},
		{
			Title:    "Larangan Memaksa Budak Wanita Berzina (Abdullah bin Ubay)",
			Narrator: "Jabir bin Abdullah radhiyallahu 'anhuma",
			SurahID:  24, AyahFrom: 33, AyahTo: 33,
			Content: "Diriwayatkan dari Jabir bin Abdullah radhiyallahu 'anhuma: Abdullah bin Ubay bin Salul (pemimpin munafik) memaksa dua budak perempuannya — Musaikah dan Umaimah — berzina untuk mendapatkan uang. Mereka mengadu kepada Rasulullah shallallahu 'alaihi wa sallam. Maka Allah menurunkan ayat: 'Janganlah kalian memaksa budak-budak perempuan kalian melakukan pelacuran sedang mereka sendiri menginginkan kesucian, karena kalian hendak mencari keuntungan duniawi.'",
			Source:  "HR. Muslim No. 3029 (di Tafsir); HR. Abu Dawud No. 2311; Shahih",
		},

		// === Batch 2: Tier 1 surat panjang ===
		{
			Title:    "Doa Penutup Al-Baqarah (Keringanan untuk Umat Muhammad)",
			Narrator: "Abu Hurairah radhiyallahu 'anhu",
			SurahID:  2, AyahFrom: 285, AyahTo: 286,
			Content: "Diriwayatkan dari Abu Hurairah radhiyallahu 'anhu: ketika turun ayat 'Wa in tubduu maa fii anfusikum aw tukhfuuhu yuhaasibkum bihillah' (QS. Al-Baqarah: 284), para sahabat datang kepada Rasulullah shallallahu 'alaihi wa sallam, berlutut, dan berkata: 'Wahai Rasulullah, kami dibebani amalan yang tidak sanggup kami lakukan: shalat, puasa, jihad, sedekah masih bisa, tapi ini ayat tentang lintasan hati...' Rasulullah menyuruh mereka mengucap 'sami'na wa atha'na' (kami dengar dan kami taat), dan setelah mereka tunduk, Allah menurunkan ayat 285-286 yang meringankan beban: 'Allah tidak membebani seseorang melainkan sesuai kesanggupannya.' Riwayat ini juga dari Ibnu Abbas dengan makna serupa.",
			Source:  "HR. Muslim No. 125-126; HR. Ahmad 2/412; Shahih",
		},
		{
			Title:    "Wanita Adalah Ladang Kalian (Bantahan terhadap Yahudi)",
			Narrator: "Jabir bin Abdullah radhiyallahu 'anhuma",
			SurahID:  2, AyahFrom: 223, AyahTo: 223,
			Content: "Diriwayatkan dari Jabir bin Abdullah radhiyallahu 'anhuma: orang-orang Yahudi berkata bahwa siapa yang mendatangi istrinya dari arah belakang (pada qubul) maka anaknya akan juling. Maka Allah menurunkan ayat: 'Istri-istri kalian adalah ladang bagi kalian, maka datangilah ladang kalian dari mana saja kalian kehendaki.' Yakni: dari arah mana pun selama tetap pada qubul (vagina), tidak masalah. Rasulullah shallallahu 'alaihi wa sallam menegaskan kebolehan dengan syarat tetap pada qubul, sedangkan dubur tetap haram (HR. Tirmidzi).",
			Source:  "HR. Bukhari No. 4528; HR. Muslim No. 1435; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Hadhanah dan Air Susu (Kompensasi Susuan)",
			Narrator: "Tafsir Shahih, Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  2, AyahFrom: 233, AyahTo: 233,
			Content: "Ayat tentang penyusuan dua tahun penuh dan hak ibu serta ayah atas anak yang disusui. Konteks turunnya berkaitan dengan permasalahan rumah tangga sahabat tentang siapa yang berkewajiban menyusui dan berapa lama. Penjelasan ayat ini diperkuat oleh hadis 'la dharara wa la dhirara' (tidak boleh memudaratkan) — Rasulullah shallallahu 'alaihi wa sallam memutuskan ibu tetap berhak atas anak selama menyusui dengan upah pantas dari ayah.",
			Source:  "Tafsir Ibnu Katsir 1/635 (riwayat dari Ibnu Abbas, jalur shahih); HR. Bukhari No. 5103 (hak ibu atas anak); Shahih",
		},
		{
			Title:    "Khamr & Maisir Tahap Pertama (Pertanyaan Umar)",
			Narrator: "Umar bin Khaththab radhiyallahu 'anhu",
			SurahID:  2, AyahFrom: 219, AyahTo: 219,
			Content: "Riwayat tahap pertama pengharaman khamr: Umar bin Khaththab radhiyallahu 'anhu pernah berdoa: 'Ya Allah, jelaskanlah kepada kami tentang khamr dengan keterangan yang memuaskan.' Maka turunlah ayat ini: 'Mereka bertanya kepadamu tentang khamr dan maisir. Katakanlah: Pada keduanya itu terdapat dosa besar dan beberapa manfaat bagi manusia, tetapi dosa keduanya lebih besar dari manfaatnya.' Setelah itu Umar berdoa lagi, lalu turun QS. An-Nisa: 43 (larangan shalat saat mabuk), kemudian akhirnya QS. Al-Maidah: 90-91 yang mengharamkan total.",
			Source:  "HR. Tirmidzi No. 3049 (hasan shahih); HR. Abu Dawud No. 3670; HR. Ahmad 1/53; Shahih oleh Al-Albani",
		},
		{
			Title:    "Tafsir Muhkam dan Mutasyabih",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  3, AyahFrom: 7, AyahTo: 7,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: Rasulullah shallallahu 'alaihi wa sallam membaca ayat ini dan bersabda: 'Apabila kalian melihat orang-orang yang mengikuti ayat-ayat mutasyabih (yang samar maknanya), maka itulah orang-orang yang Allah sebut (sebagai orang yang dalam hatinya ada kecondongan kepada kesesatan), maka berhati-hatilah dari mereka.' Konteks turunnya: terkait dialog dengan delegasi Nasrani Najran yang berdebat tentang Isa 'alaihissalam menggunakan ayat-ayat mutasyabih. Allah menurunkan ayat ini sebagai patokan: ikuti yang muhkam (jelas), kembalikan yang mutasyabih kepada-Nya.",
			Source:  "HR. Bukhari No. 4547; HR. Muslim No. 2665; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Tidak Ada Urusan Bagimu (Setelah Uhud)",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  3, AyahFrom: 128, AyahTo: 129,
			Content: "Diriwayatkan dari Anas bin Malik radhiyallahu 'anhu: ketika gigi seri Rasulullah shallallahu 'alaihi wa sallam patah saat perang Uhud, dan wajah beliau dilukai, beliau mengatakan: 'Bagaimana kaum yang melukai wajah Nabi mereka akan beruntung?' (Riwayat lain: beliau mendoakan keburukan untuk mereka). Maka Allah menurunkan ayat: 'Tidak ada sedikit pun urusan campur tanganmu dalam urusan mereka itu — atau Allah menerima taubat mereka, atau mengazab mereka, karena sesungguhnya mereka itu zalim.' Setelahnya, beberapa di antara mereka (Khalid bin Walid, 'Ikrimah, Abu Sufyan) masuk Islam.",
			Source:  "HR. Bukhari No. 4068, 4069; HR. Muslim No. 1791; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Mengantuk Saat Uhud (Ketenangan dari Allah)",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  3, AyahFrom: 154, AyahTo: 154,
			Content: "Diriwayatkan dari Anas bin Malik radhiyallahu 'anhu: ayat 'Kemudian setelah kamu ditimpa kesedihan itu, Allah menurunkan rasa aman atas kalian berupa kantuk yang meliputi segolongan dari kalian' turun berkenaan dengan apa yang dialami para sahabat di hari Uhud. Abu Thalhah radhiyallahu 'anhu berkata: 'Aku adalah salah seorang yang dikuasai kantuk pada hari Uhud sampai pedangku terjatuh dari tanganku berkali-kali, lalu aku ambil kembali, lalu jatuh lagi.' Sementara kelompok munafik tetap dalam ketakutan dan keraguan.",
			Source:  "HR. Bukhari No. 4068; HR. Tirmidzi No. 3007 (hasan shahih); Shahih",
		},
		{
			Title:    "Larangan Mewarisi Istri Secara Paksa (Tradisi Jahiliah)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  4, AyahFrom: 19, AyahTo: 19,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: di masa jahiliah, jika seorang lelaki Anshar wafat, maka ahli warisnya yang paling utama mengambil istrinya — boleh dinikahi tanpa mahar baru, atau dilarang menikahi orang lain sampai meninggal, atau ditahan untuk dimintai tebusan. Ketika Islam datang, Allah menurunkan ayat ini melarang praktik tersebut: wanita tidak boleh diwariskan secara paksa, dan tidak boleh diperlakukan dengan paksaan untuk mengambil sebagian dari mahar yang sudah diberikan.",
			Source:  "HR. Bukhari No. 4579, 6948; HR. Abu Dawud No. 2089; Shahih",
		},
		{
			Title:    "Pengharaman Mut'ah (Khaibar)",
			Narrator: "Ali bin Abi Thalib radhiyallahu 'anhu (via Sabrah Al-Juhani)",
			SurahID:  4, AyahFrom: 24, AyahTo: 24,
			Content: "Diriwayatkan dari Ali bin Abi Thalib radhiyallahu 'anhu: 'Rasulullah shallallahu 'alaihi wa sallam mengharamkan mut'ah (nikah kontrak) dan daging keledai jinak pada hari Khaibar.' Riwayat dari Sabrah bin Ma'bad Al-Juhani radhiyallahu 'anhu menambahkan: pada saat Fathu Mekah, Rasulullah pernah membolehkan mut'ah selama tiga hari, lalu beliau mengharamkannya untuk selamanya hingga hari kiamat. Ayat ini awalnya membolehkan mut'ah dalam konteks tertentu, lalu hukumnya dimansukh oleh sabda Nabi.",
			Source:  "HR. Bukhari No. 4216, 5115; HR. Muslim No. 1407 (Ali); HR. Muslim No. 1406 (Sabrah); Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Wanita Ingin Pahala Jihad seperti Lelaki",
			Narrator: "Ummu Salamah radhiyallahu 'anha",
			SurahID:  4, AyahFrom: 32, AyahTo: 32,
			Content: "Diriwayatkan dari Ummu Salamah radhiyallahu 'anha: aku bertanya: 'Wahai Rasulullah, kaum lelaki ikut perang sedangkan kami tidak, dan mereka mendapat warisan dua bagian sedangkan kami satu bagian.' Maka Allah menurunkan ayat: 'Janganlah kalian iri terhadap apa yang Allah karuniakan kepada sebagian kalian melebihi sebagian yang lain. Bagi laki-laki ada bagian dari apa yang mereka usahakan, dan bagi wanita ada bagian dari apa yang mereka usahakan.' Allah menetapkan amal masing-masing sesuai keadaan, dan setiap kebajikan akan mendapat balasan.",
			Source:  "HR. Tirmidzi No. 3022 (hasan shahih); HR. Hakim 2/305 (shahih); Shahih oleh Al-Albani",
		},
		{
			Title:    "Munafik di Antara Kaum (Pertikaian Pendapat tentang Mereka)",
			Narrator: "Zaid bin Tsabit radhiyallahu 'anhu",
			SurahID:  4, AyahFrom: 88, AyahTo: 88,
			Content: "Diriwayatkan dari Zaid bin Tsabit radhiyallahu 'anhu: ketika Rasulullah shallallahu 'alaihi wa sallam keluar untuk perang Uhud, sekelompok orang yang ikut dengannya berpaling kembali ke Madinah. Para sahabat berselisih tentang mereka: sebagian berkata 'mereka kafir, kita perangi'; sebagian berkata 'mereka mukmin, kita biarkan'. Maka Allah menurunkan ayat ini: 'Mengapa kalian terbagi menjadi dua golongan dalam menghadapi orang-orang munafik...' Rasulullah bersabda: 'Sesungguhnya Madinah ini adalah pembersih, ia membersihkan kotoran sebagaimana api membersihkan kotoran perak.'",
			Source:  "HR. Bukhari No. 4589, 1884; HR. Muslim No. 1384; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Kalalah (Pertanyaan Jabir Saat Sakit)",
			Narrator: "Jabir bin Abdullah radhiyallahu 'anhuma",
			SurahID:  4, AyahFrom: 176, AyahTo: 176,
			Content: "Diriwayatkan dari Jabir bin Abdullah radhiyallahu 'anhuma: aku sakit, dan Rasulullah shallallahu 'alaihi wa sallam menjengukku. Ibuku bertanya: 'Wahai Rasulullah, bagaimana aku bagi harta bila Jabir wafat?' (saat itu Jabir hanya punya saudara perempuan, tidak punya anak atau ayah). Aku berkata: 'Wahai Rasulullah, tidak diturunkan kecuali ayat tentang kalalah.' Maka Allah menurunkan ayat akhir An-Nisa: 'Mereka meminta fatwa kepadamu (tentang kalalah). Katakanlah: Allah memberi fatwa kepada kalian tentang kalalah...' Inilah ayat terakhir yang turun tentang waris.",
			Source:  "HR. Bukhari No. 194, 4577; HR. Muslim No. 1616; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Hujjah Ka'b bin Malik & Tobat Tiga Sahabat yang Tertinggal",
			Narrator: "Ka'b bin Malik radhiyallahu 'anhu",
			SurahID:  9, AyahFrom: 117, AyahTo: 118,
			Content: "Riwayat panjang Ka'b bin Malik radhiyallahu 'anhu: dia, Murarah bin Rabi', dan Hilal bin Umayyah tertinggal dari perang Tabuk tanpa udzur sah. Setelah Rasulullah shallallahu 'alaihi wa sallam pulang, mereka jujur mengakui kesalahan, sementara para munafik membuat-buat alasan dusta. Rasulullah memerintahkan kaum muslimin tidak berbicara dengan ketiganya. Selama 50 hari mereka diisolasi, hingga bumi yang luas terasa sempit. Lalu Allah menurunkan ayat 117-118 yang menerima tobat mereka. Ka'b berkata: 'Demi Allah, tidak ada nikmat yang Allah berikan padaku setelah Islam yang lebih besar daripada kejujuranku kepada Rasulullah hari itu.'",
			Source:  "HR. Bukhari No. 4418, 6690; HR. Muslim No. 2769; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Hari Hunain & Pasukan yang Banyak",
			Narrator: "Al-Bara' bin 'Azib radhiyallahu 'anhu",
			SurahID:  9, AyahFrom: 25, AyahTo: 26,
			Content: "Diriwayatkan dari Al-Bara' bin 'Azib radhiyallahu 'anhu: ada seseorang yang berkata kepadanya: 'Apakah kalian lari saat hari Hunain wahai Abu Umarah?' Beliau menjawab: 'Tidak, demi Allah, Rasulullah shallallahu 'alaihi wa sallam tidak berpaling. Tapi sebagian pasukan yang baru saja masuk Islam terburu-buru maju, lalu disambut musuh dengan panah bertubi-tubi.' Saat itu Rasulullah berada di atas baghal putihnya sambil bersabda: 'Aku adalah Nabi tanpa dusta, aku adalah putra Abdul Muthallib.' Allah menurunkan ayat ini mengingatkan kemenangan setelah pasukan muslim sempat goyah.",
			Source:  "HR. Bukhari No. 4315; HR. Muslim No. 1776; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Sihir Labid bin A'sham (Al-Mu'awwidzatain)",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  113, AyahFrom: 1, AyahTo: 5,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: Rasulullah shallallahu 'alaihi wa sallam pernah disihir oleh Labid bin A'sham — seorang Yahudi dari Bani Zuraiq — sampai-sampai beliau merasa seakan melakukan sesuatu padahal tidak. Suatu malam, dua malaikat datang dalam mimpi memberitahu lokasi sihir di sumur Dzarwan, di bawah batu, dalam seludang mayang kurma. Rasulullah dan sahabat mengeluarkannya. Allah menurunkan dua surat Al-Mu'awwidzatain (Al-Falaq dan An-Nas), dan Rasulullah membacanya hingga sehat sempurna. Inilah sebab nuzul utama untuk dua surat tersebut.",
			Source:  "HR. Bukhari No. 3268, 5763; HR. Muslim No. 2189; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Sihir Labid bin A'sham (An-Nas)",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  114, AyahFrom: 1, AyahTo: 6,
			Content: "Sebab nuzul yang sama dengan Al-Falaq: peristiwa sihir Labid bin A'sham terhadap Rasulullah shallallahu 'alaihi wa sallam. Allah menurunkan kedua surat (Al-Falaq dan An-Nas) sebagai 'al-mu'awwidzatain' (dua surat perlindungan). Aisyah radhiyallahu 'anha berkata: 'Rasulullah ketika berbaring di tempat tidurnya setiap malam, beliau menyatukan kedua telapak tangannya, lalu meniupnya dan membaca Qul huwallahu ahad, Qul a'udzu birabbil falaq, dan Qul a'udzu birabbin nas, kemudian mengusap apa yang dapat dijangkau dari tubuhnya, dimulai dari kepala, wajah, dan bagian depan tubuh. Beliau melakukannya tiga kali.'",
			Source:  "HR. Bukhari No. 5017, 3268; HR. Muslim No. 2189; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Pertanyaan Quraisy tentang Nasab Tuhan (Al-Ikhlas)",
			Narrator: "Ubay bin Ka'b radhiyallahu 'anhu",
			SurahID:  112, AyahFrom: 1, AyahTo: 4,
			Content: "Diriwayatkan dari Ubay bin Ka'b radhiyallahu 'anhu: orang-orang musyrik berkata kepada Rasulullah shallallahu 'alaihi wa sallam: 'Wahai Muhammad, sebutkan nasab Tuhanmu kepada kami!' Maka Allah menurunkan: 'Qul huwallaahu ahad, Allahu shamad, lam yalid wa lam yuulad, wa lam yakul lahu kufuwan ahad.' (Katakanlah: Dialah Allah, Yang Maha Esa. Allah tempat bergantung. Dia tidak beranak dan tidak diperanakkan. Dan tidak ada satupun yang setara dengan-Nya). Surat ini setara nilainya dengan sepertiga Al-Qur'an dalam riwayat lain.",
			Source:  "HR. Tirmidzi No. 3364 (hasan shahih); HR. Ahmad 5/133-134; Hasan Shahih oleh Al-Albani",
		},
		{
			Title:    "Tobat Penuduh Zina (Mistah bin Utsatsah)",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  24, AyahFrom: 22, AyahTo: 22,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha sebagai lanjutan peristiwa Al-Ifk: setelah Allah membersihkan nama Aisyah, Abu Bakar Ash-Shiddiq radhiyallahu 'anhu bersumpah tidak akan lagi memberi nafkah kepada Mistah bin Utsatsah (kerabatnya) yang telah ikut menyebar fitnah. Maka Allah menurunkan ayat ini: 'Dan janganlah orang-orang yang mempunyai kelebihan dan kelapangan di antara kalian bersumpah bahwa mereka tidak akan memberi (bantuan) kepada kerabat...' Abu Bakar berkata: 'Demi Allah, sungguh aku ingin Allah mengampuniku!' Lalu beliau mengembalikan nafkah Mistah dan berkata: 'Demi Allah, aku tidak akan mencabutnya selama-lamanya.'",
			Source:  "HR. Bukhari No. 4757; HR. Muslim No. 2770; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Adab Meminta Izin Masuk Rumah",
			Narrator: "Sahl bin Sa'd radhiyallahu 'anhu",
			SurahID:  24, AyahFrom: 27, AyahTo: 28,
			Content: "Diriwayatkan dari Sahl bin Sa'd radhiyallahu 'anhu: seseorang melongok ke kamar Rasulullah shallallahu 'alaihi wa sallam dari celah pintu, sementara di tangan Nabi ada sisir untuk merapikan rambut. Rasulullah bersabda: 'Andai aku tahu engkau melihatku, niscaya kucucuk matamu dengan sisir ini. Sesungguhnya izin (masuk) itu disyariatkan karena penglihatan.' Maka Allah menurunkan ayat ini tentang adab meminta izin: 'Wahai orang-orang yang beriman, janganlah kalian masuk ke rumah selain rumah kalian sebelum kalian meminta izin dan memberi salam kepada penghuninya.'",
			Source:  "HR. Bukhari No. 6241; HR. Muslim No. 2156; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Sahabat yang Menepati Janji (Anas bin Nadhr)",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  33, AyahFrom: 23, AyahTo: 23,
			Content: "Diriwayatkan dari Anas bin Malik radhiyallahu 'anhu: pamanku Anas bin Nadhr radhiyallahu 'anhu tidak ikut perang Badar. Beliau berkata: 'Wahai Rasulullah, aku tidak hadir di perang pertama, dan jika Allah mempertemukan aku dengan musuh, niscaya Allah akan melihat apa yang akan kulakukan.' Pada perang Uhud, beliau berpapasan dengan Sa'd bin Mu'adz dan berkata: 'Demi Tuhannya Nadhr, sungguh aku mencium aroma surga di balik Uhud!' Beliau berperang sampai gugur syahid, dan ditemukan padanya 80 lebih luka tusukan dan tebasan. Adiknya tidak mengenali jasadnya kecuali dari ujung jarinya. Maka Allah menurunkan ayat ini.",
			Source:  "HR. Bukhari No. 2805, 4783; HR. Muslim No. 1903; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Pembersihan Ahlul Bait (Khamis Al-Kisa')",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  33, AyahFrom: 33, AyahTo: 33,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: Rasulullah shallallahu 'alaihi wa sallam keluar di pagi hari mengenakan kain bergaris hitam dari bulu domba. Lalu datang Hasan bin Ali, dan beliau memasukkannya. Lalu datang Husain bin Ali, dan beliau memasukkannya bersama Hasan. Lalu datang Fathimah, dan beliau memasukkannya. Lalu datang Ali, dan beliau memasukkannya. Kemudian beliau membaca: 'Innamaa yuriidullaahu liyudzhiba 'ankumur rijsa ahlal bayti wa yuthahhirakum tath-hiiraa.' (Sesungguhnya Allah berkehendak menghilangkan kotoran dari kalian, wahai Ahlul Bait, dan menyucikan kalian sesuci-sucinya).",
			Source:  "HR. Muslim No. 2424; HR. Tirmidzi No. 3205 (hasan shahih); Shahih",
		},
		{
			Title:    "Walid bin 'Uqbah & Bani Mushthaliq (Tabayyun)",
			Narrator: "Al-Harits bin Dhirar radhiyallahu 'anhu",
			SurahID:  49, AyahFrom: 6, AyahTo: 6,
			Content: "Diriwayatkan dari Al-Harits bin Dhirar Al-Khuza'i radhiyallahu 'anhu: aku menemui Rasulullah shallallahu 'alaihi wa sallam dan menyatakan keislaman serta janji untuk mengumpulkan zakat dari kaumku. Rasulullah mengutus Walid bin 'Uqbah untuk mengambil zakat di waktu yang telah ditentukan. Saat dekat ke kampung kami, Walid takut (karena ada permusuhan lama) dan kembali. Walid melaporkan dusta bahwa kami menolak zakat dan ingin membunuhnya. Rasulullah hampir mengirim pasukan, lalu Allah menurunkan ayat ini memerintahkan tabayyun: 'Wahai orang-orang beriman, jika datang kepada kalian orang fasik membawa berita, maka periksalah kebenarannya...'",
			Source:  "HR. Ahmad 4/279 (hasan); HR. Thabrani; Hasan dengan dukungan jalur lain; Tafsir Ibnu Katsir",
		},
		{
			Title:    "Larangan Mengejek Kaum Lain (Bani Tamim)",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  49, AyahFrom: 11, AyahTo: 11,
			Content: "Diriwayatkan dari Anas bin Malik radhiyallahu 'anhu: ayat ini turun berkenaan dengan Bani Tamim yang mengejek sebagian sahabat (Bilal, Khabbab, Ammar, Salman) karena dahulunya budak/maula. Sebagian wanita Anshar juga sempat mengejek Ummu Salamah. Maka Allah menurunkan: 'Wahai orang-orang yang beriman, janganlah suatu kaum mengejek kaum yang lain, karena boleh jadi mereka yang diejek lebih baik...' dan melarang panggilan dengan gelar buruk.",
			Source:  "HR. Tirmidzi No. 3268 (hasan shahih); HR. Abu Dawud No. 4962; Shahih oleh Al-Albani",
		},
		{
			Title:    "Tafsir Bilal al-Habasyi & Persaudaraan (49:13)",
			Narrator: "Tafsir Bukhari, Abdullah bin Umar radhiyallahu 'anhuma",
			SurahID:  49, AyahFrom: 13, AyahTo: 13,
			Content: "Diriwayatkan dalam beberapa jalur: ayat ini turun saat Fathu Mekah, ketika Bilal radhiyallahu 'anhu naik ke atas Ka'bah untuk adzan. Sebagian Quraisy berkata: 'Apakah Muhammad tidak menemukan selain burung gagak hitam ini untuk azan?' Yang lain berkata: 'Jika Allah memurkainya, niscaya akan mengganti dia.' Lalu Allah menurunkan ayat ini menetapkan kemuliaan manusia berdasarkan ketakwaan, bukan keturunan. Rasulullah shallallahu 'alaihi wa sallam menegaskan: 'Sesungguhnya Allah telah menghilangkan dari kalian kesombongan jahiliah dan membanggakan nenek moyang.'",
			Source:  "HR. Abu Dawud No. 5116; HR. Tirmidzi No. 3270; Hasan; HR. Bukhari No. 4905 (Bilal); Tafsir Ibnu Katsir 4/217",
		},
		{
			Title:    "Jangan Cepat Membaca Wahyu (Tafsir Al-Qiyamah lengkap)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  20, AyahFrom: 114, AyahTo: 114,
			Content: "Tafsir paralel: ayat ini di Thaha juga melarang Nabi shallallahu 'alaihi wa sallam tergesa-gesa membaca Al-Qur'an sebelum Jibril 'alaihissalam selesai membacakan. Dari Ibnu Abbas radhiyallahu 'anhuma: Rasulullah dahulu menggerakkan kedua bibirnya saat menerima wahyu khawatir lupa. Maka Allah menurunkan ayat 'Wa la ta'jal bil qur'ani min qabli an yuqdha ilayka wahyuhu' di surat Thaha sebagai paralel dengan Al-Qiyamah 16-19. Setelah itu, beliau diam mendengarkan dan baru mengulang setelah Jibril selesai.",
			Source:  "HR. Bukhari No. 5; HR. Muslim No. 448; Tafsir Ibnu Katsir 5/325; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Sa'al Sa'ilun (Permintaan Adzab Nadhr bin Harits)",
			Narrator: "Tafsir, Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  70, AyahFrom: 1, AyahTo: 3,
			Content: "Diriwayatkan: An-Nadhr bin Al-Harits — salah satu tokoh Quraisy yang amat memusuhi Nabi — pernah berkata: 'Ya Allah, jika benar (Al-Qur'an) ini dari sisi-Mu, maka turunkanlah hujan batu kepada kami atau datangkanlah azab yang pedih.' Maka Allah menurunkan ayat: 'Seseorang telah meminta datangnya azab yang akan terjadi, untuk orang-orang kafir.' Nadhr bin Harits akhirnya tewas sebagai tawanan setelah perang Badar dan dieksekusi atas perintah Rasulullah karena permusuhan yang berat.",
			Source:  "HR. Nasai dalam As-Sunan Al-Kubra No. 11297; HR. Hakim 2/502 (shahih); Tafsir Ibnu Katsir 8/220; Shahih oleh Al-Albani",
		},
		{
			Title:    "Ujian Hatib bin Abi Balta'ah (Lanjutan)",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  60, AyahFrom: 12, AyahTo: 12,
			Content: "Riwayat lanjutan dari surat Al-Mumtahanah: setelah peristiwa Hatib dan Fathu Mekah, datang utusan wanita musyrikah ingin berbai'at masuk Islam. Rasulullah shallallahu 'alaihi wa sallam membai'at mereka berdasarkan ayat 12 ini: tidak menyekutukan Allah, tidak mencuri, tidak berzina, tidak membunuh anak, tidak membuat-buat kebohongan, dan tidak mendurhakai dalam kebaikan. Bai'at ini dilakukan dengan kata-kata, tanpa berjabat tangan langsung dengan wanita yang bukan mahram.",
			Source:  "HR. Bukhari No. 7214, 4892; HR. Muslim No. 1866; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Pedagang Curang di Madinah (Surat Al-Muthaffifin)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  83, AyahFrom: 1, AyahTo: 3,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: ketika Rasulullah shallallahu 'alaihi wa sallam tiba di Madinah, penduduknya termasuk pedagang yang paling buruk takarannya dalam jual beli. Maka Allah menurunkan: 'Celakalah bagi al-muthaffifiin (orang-orang yang curang takarannya)!' Setelah itu, mereka memperbaiki takaran dan timbangan, sampai dikenal sebagai yang paling baik takarannya. Riwayat ini menjadi salah satu contoh perubahan akhlak yang dibawa wahyu.",
			Source:  "HR. Nasai No. 4685; HR. Ibnu Majah No. 2223; Shahih oleh Al-Albani; Tafsir Ibnu Katsir 8/345",
		},
		{
			Title:    "Ashabul Ukhdud (Anak Muda dan Raja Zalim)",
			Narrator: "Shuhaib Ar-Rumi radhiyallahu 'anhu",
			SurahID:  85, AyahFrom: 4, AyahTo: 8,
			Content: "Hadis panjang dari Shuhaib radhiyallahu 'anhu: Rasulullah shallallahu 'alaihi wa sallam menceritakan kisah seorang raja zalim, tukang sihir tua, anak muda yang masuk Islam lewat ajaran seorang rahib. Anak muda itu sabar dihadapkan pada berbagai siksaan: dilempar dari tebing, ditenggelamkan, sampai akhirnya dibunuh dengan panah atas namanya sendiri di hadapan keramaian. Setelah dia gugur syahid, seluruh penduduk negeri itu beriman. Sang raja murka, lalu menggali parit-parit (al-ukhdud), menyalakan api, dan melemparkan kaum mukmin ke dalamnya. Allah menurunkan ayat-ayat ini sebagai peringatan tentang kesabaran orang beriman dan kebinasaan para zalim.",
			Source:  "HR. Muslim No. 3005 (riwayat panjang Shuhaib); HR. Tirmidzi No. 3340; Shahih",
		},

		// === Batch 3: Tier 2 — Madaniyyah & klasik Mekah ===
		{
			Title:    "Hari-Hari Itu Kami Pergilirkan (Pelajaran dari Uhud)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  3, AyahFrom: 140, AyahTo: 142,
			Content: "Ayat ini turun setelah Uhud sebagai penghibur bagi kaum muslimin yang ditimpa kekalahan dan kesedihan. Allah menjelaskan: jika kalian menderita luka, maka kaum kafir pun menderita luka serupa di hari Badar. Hari-hari (kemenangan dan kekalahan) itu Kami pergilirkan di antara manusia, agar Allah membedakan orang-orang beriman, dan agar sebagian kalian Dia jadikan syuhada (yang gugur dalam perang). Riwayat sebab nuzul ini diperkuat oleh konteks penuturan Bukhari/Muslim tentang Uhud dari Anas dan Ibnu Abbas.",
			Source:  "HR. Bukhari No. 4067-4071; HR. Muslim No. 1791; Tafsir Ibnu Katsir 2/127; Shahih (konteks Muttafaq 'alaih)",
		},
		{
			Title:    "Hamra'ul Asad (Sahabat yang Memenuhi Panggilan Setelah Uhud)",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  3, AyahFrom: 172, AyahTo: 174,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha kepada putranya 'Urwah bin Zubair: bahwa dua orang ayahmu (Zubair bin Awwam dan Abu Bakar) termasuk dalam ayat ini. Setelah perang Uhud yang berat, ketika Quraisy bergerak balik dengan niat menyerang Madinah, Rasulullah shallallahu 'alaihi wa sallam menyeru sahabat untuk mengejar musuh sampai ke Hamra'ul Asad. Walaupun terluka dan letih, kaum mukmin tetap menjawab panggilan dan keluar bersama Rasulullah. Allah memuji mereka dengan ayat ini: '(Yaitu) orang-orang yang menjawab panggilan Allah dan Rasul setelah mereka mendapat luka...'",
			Source:  "HR. Bukhari No. 4077; HR. Muslim No. 2418; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Yahudi Berkata 'Allah Miskin'",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  3, AyahFrom: 181, AyahTo: 181,
			Content: "Diriwayatkan: ketika turun ayat 'Man dzal ladzi yuqridhullaaha qardhan hasanan' (QS. Al-Baqarah: 245), Yahudi (di antaranya Finhash) berkata dengan ejekan: 'Sungguh Tuhan Muhammad miskin, sampai-sampai meminta pinjaman pada hamba-Nya!' Maka Allah menurunkan: 'Sungguh Allah telah mendengar ucapan orang-orang yang mengatakan: Allah itu miskin dan kami kaya. Akan Kami tulis perkataan mereka dan pembunuhan mereka terhadap para nabi tanpa hak...' Sebagai bantahan tegas atas penghinaan tersebut.",
			Source:  "HR. Ahmad 1/300; HR. Hakim 2/300 (shahih); HR. Ibnu Abi Hatim; Shahih oleh Al-Albani; Tafsir Ibnu Katsir 2/167",
		},
		{
			Title:    "Sungguh Kalian Akan Diuji dengan Harta dan Diri (Yahudi & Ka'b bin Asyraf)",
			Narrator: "Usamah bin Zaid radhiyallahu 'anhuma",
			SurahID:  3, AyahFrom: 186, AyahTo: 186,
			Content: "Diriwayatkan dari Usamah bin Zaid radhiyallahu 'anhuma: Rasulullah shallallahu 'alaihi wa sallam dan para sahabat melewati majelis yang campur antara muslim, Yahudi, dan musyrikin (yang dipimpin Abdullah bin Ubay dan termasuk Ka'b bin Al-Asyraf). Ketika beliau membacakan Al-Qur'an dan mengajak mereka kepada Allah, Abdullah bin Ubay berkata kasar. Sa'd bin Mu'adz menjawab dengan tenang. Maka Allah menurunkan ayat ini sebagai bekal kesabaran bagi kaum muslimin: 'Sungguh kalian pasti akan diuji terhadap harta dan diri kalian, dan sungguh kalian akan mendengar dari ahli kitab dan musyrikin perkataan yang menyakitkan hati. Jika kalian sabar dan bertakwa, maka itu termasuk urusan yang patut diutamakan.'",
			Source:  "HR. Bukhari No. 4566, 6207; HR. Muslim No. 1798; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Munafik yang Bangga atas Apa yang Tidak Dia Lakukan",
			Narrator: "Abu Sa'id Al-Khudri radhiyallahu 'anhu",
			SurahID:  3, AyahFrom: 188, AyahTo: 188,
			Content: "Diriwayatkan dari Abu Sa'id Al-Khudri radhiyallahu 'anhu: di masa Rasulullah shallallahu 'alaihi wa sallam, ada sekelompok munafik yang bila Rasulullah keluar untuk perang, mereka tidak ikut serta lalu bersuka cita karena tertinggal. Bila Rasulullah pulang, mereka membuat-buat alasan dan ingin dipuji atas apa yang tidak mereka lakukan. Maka Allah menurunkan ayat ini: 'Janganlah engkau menyangka bahwa orang-orang yang gembira dengan apa yang mereka kerjakan, dan suka dipuji atas apa yang belum mereka kerjakan, terlepas dari azab...' Dalam riwayat lain ayat ini juga ditujukan kepada Yahudi yang menyembunyikan kebenaran lalu mengaku-aku.",
			Source:  "HR. Bukhari No. 4567, 4568; HR. Muslim No. 2778; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Doa Malam Rasulullah & Penciptaan Langit",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  3, AyahFrom: 190, AyahTo: 191,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: aku menginap di rumah bibiku Maimunah radhiyallahu 'anha (istri Nabi). Rasulullah shallallahu 'alaihi wa sallam tidur di awal malam, lalu bangun di akhir malam, melihat langit, dan membaca sepuluh ayat terakhir surat Ali 'Imran (190-200), dimulai dengan: 'Inna fi khalqis-samaawaati wal-ardhi wakhtilaafil-laili wan-nahaari la-aayaatil li ulil albaab.' Dalam riwayat lain disebutkan ayat ini turun saat orang Quraisy meminta tanda kebesaran, lalu Allah mengarahkan pandangan kepada penciptaan langit dan bumi sebagai tanda yang jelas.",
			Source:  "HR. Bukhari No. 183, 4569; HR. Muslim No. 763; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Larangan Bunuh Diri (Tayammum 'Amr bin Al-'Ash)",
			Narrator: "'Amr bin Al-'Ash radhiyallahu 'anhu",
			SurahID:  4, AyahFrom: 29, AyahTo: 29,
			Content: "Diriwayatkan dari 'Amr bin Al-'Ash radhiyallahu 'anhu: dalam Sariyyah Dzatus Salasil di malam yang sangat dingin, aku junub. Khawatir mati jika mandi dengan air dingin, aku tayammum lalu shalat Shubuh sebagai imam. Sesampai di Madinah, kuceritakan kepada Rasulullah shallallahu 'alaihi wa sallam. Beliau bertanya: 'Engkau shalat dengan sahabatmu padahal junub?' Aku menjawab: 'Aku ingat firman Allah Wa la taqtuluu anfusakum innallaaha kaana bikum rahiimaa (jangan kalian membunuh diri sendiri, sungguh Allah Maha Penyayang).' Rasulullah pun tertawa dan tidak mengucapkan apa-apa, sebagai pengakuan atas ijtihadnya.",
			Source:  "HR. Abu Dawud No. 334; HR. Ahmad 4/203; HR. Daraquthni 1/178; Shahih oleh Al-Albani; Bukhari menyebutkan secara mu'allaq No. 345",
		},
		{
			Title:    "Pertanyaan tentang Wanita Yatim & Hak Mereka",
			Narrator: "Aisyah radhiyallahu 'anha",
			SurahID:  4, AyahFrom: 127, AyahTo: 127,
			Content: "Diriwayatkan dari Aisyah radhiyallahu 'anha: 'Urwah bertanya kepadaku tentang ayat ini, dan aku menjawab: Wahai keponakanku, ini tentang anak wanita yatim yang berada dalam pengasuhan walinya, dan walinya tertarik karena harta dan kecantikannya, lalu ingin menikahinya tanpa memberikan mahar yang setara dengan wanita selainnya. Mereka dilarang menikahi anak yatim itu kecuali memberikan mahar yang adil, atau menikahkannya dengan lelaki lain. Setelah ayat ini, manusia bertanya lagi pada Rasulullah, lalu Allah menurunkan ayat ini sebagai penegasan keadilan terhadap wanita yatim.",
			Source:  "HR. Bukhari No. 5064, 4574; HR. Muslim No. 3018; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Larangan Banyak Bertanya (Sa'd bin Abi Waqqash & Abdullah bin Hudzafah)",
			Narrator: "Sa'd bin Abi Waqqash radhiyallahu 'anhu",
			SurahID:  5, AyahFrom: 101, AyahTo: 102,
			Content: "Diriwayatkan dari Sa'd bin Abi Waqqash radhiyallahu 'anhu: dosa muslim yang paling besar adalah dia bertanya tentang sesuatu yang tidak diharamkan, lalu menjadi diharamkan karena pertanyaannya. Dalam riwayat Bukhari/Muslim dari Anas: Rasulullah shallallahu 'alaihi wa sallam sedang khutbah, lalu seseorang bertanya: 'Siapa ayahku wahai Rasulullah?' Beliau menjawab: 'Ayahmu Hudzafah!' (membuat malu orang yang bertanya). Dalam kemarahan Nabi, Umar berkata: 'Kami ridha Allah sebagai Tuhan, Islam sebagai agama, dan Muhammad sebagai Nabi.' Maka Allah menurunkan ayat ini melarang banyak bertanya tentang hal yang bila dijelaskan akan menyusahkan.",
			Source:  "HR. Bukhari No. 7295, 540; HR. Muslim No. 2359, 2358; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Allah Meringankan Beban Perang (Awal Madinah)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  8, AyahFrom: 65, AyahTo: 66,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: ketika turun ayat 'Jika ada di antara kalian dua puluh yang sabar, niscaya akan mengalahkan dua ratus' (8:65), kewajiban itu terasa berat bagi kaum muslimin — satu lawan sepuluh. Maka Allah meringankannya dengan ayat 8:66: 'Sekarang Allah telah meringankan beban kalian; Dia tahu ada kelemahan pada kalian. Maka jika ada seratus orang yang sabar di antara kalian, niscaya akan mengalahkan dua ratus.' Yakni rasio menjadi satu lawan dua, sesuai keadaan kaum muslimin saat itu.",
			Source:  "HR. Bukhari No. 4652-4653; HR. Abu Dawud No. 2646; Shahih",
		},
		{
			Title:    "Perselisihan tentang Tawanan Perang Badar",
			Narrator: "Umar bin Khaththab radhiyallahu 'anhu",
			SurahID:  8, AyahFrom: 67, AyahTo: 68,
			Content: "Diriwayatkan dari Umar bin Khaththab radhiyallahu 'anhu: pada perang Badar, setelah Allah memberi kemenangan, Rasulullah shallallahu 'alaihi wa sallam meminta pendapat para sahabat tentang tawanan. Abu Bakar mengusulkan tebusan agar mereka kelak masuk Islam; Umar mengusulkan dieksekusi karena mereka pemimpin kekufuran. Rasulullah memilih pendapat Abu Bakar dan menerima tebusan. Keesokan harinya Umar mendapati Rasulullah dan Abu Bakar menangis. Beliau bersabda: 'Telah disodorkan kepadaku azab atas sahabatku karena tebusan, lebih dekat dari pohon ini.' Maka Allah menurunkan ayat: 'Tidak patut bagi seorang Nabi memiliki tawanan sebelum dia melumpuhkan musuhnya di muka bumi...'",
			Source:  "HR. Muslim No. 1763; HR. Tirmidzi No. 3084 (hasan shahih); HR. Ahmad 1/30; Shahih",
		},
		{
			Title:    "Bara'ah & Pengumuman Larangan Musyrik di Tanah Haram",
			Narrator: "Abu Hurairah radhiyallahu 'anhu",
			SurahID:  9, AyahFrom: 1, AyahTo: 5,
			Content: "Diriwayatkan dari Abu Hurairah radhiyallahu 'anhu: Rasulullah shallallahu 'alaihi wa sallam mengutus Abu Bakar Ash-Shiddiq sebagai amir haji tahun ke-9 H, lalu menyusulinya dengan Ali bin Abi Thalib radhiyallahu 'anhu untuk membawa surat Al-Bara'ah dan membacakannya kepada manusia di hari Nahr. Pengumuman: tidak ada lagi musyrikin yang boleh berhaji setelah tahun ini, dan tidak boleh thawaf telanjang. Inilah pemutusan janji dengan musyrikin yang melanggar perjanjian. Setelah masa empat bulan haram lewat, kaum muslimin diperintahkan memerangi mereka yang tetap musyrik, kecuali yang berkomitmen pada perjanjian.",
			Source:  "HR. Bukhari No. 369, 4655; HR. Muslim No. 1347; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Munafik Tidak Ikut Tabuk dengan Berbagai Alasan",
			Narrator: "Ka'b bin Malik radhiyallahu 'anhu",
			SurahID:  9, AyahFrom: 42, AyahTo: 42,
			Content: "Konteks dari riwayat panjang Ka'b bin Malik tentang perang Tabuk: Rasulullah shallallahu 'alaihi wa sallam mengajak seluruh sahabat keluar dalam panas dan jarak yang jauh menuju Tabuk. Banyak munafik membuat-buat alasan untuk tidak ikut. Maka Allah menurunkan ayat ini menyibak kepalsuan mereka: 'Seandainya yang engkau ajak itu keuntungan yang dekat dan perjalanan yang ringan, tentu mereka mengikutimu, tetapi yang jauh terasa berat bagi mereka. Mereka akan bersumpah palsu atas nama Allah: Andai kami sanggup tentu kami berangkat bersama kalian. Mereka membinasakan diri sendiri, dan Allah tahu sungguh mereka itu pendusta.'",
			Source:  "HR. Bukhari No. 4418 (riwayat panjang Ka'b); HR. Muslim No. 2769; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Munafik Mengejek Sahabat yang Bersedekah (Abu 'Aqil)",
			Narrator: "Abu Mas'ud Al-Badri radhiyallahu 'anhu",
			SurahID:  9, AyahFrom: 79, AyahTo: 79,
			Content: "Diriwayatkan dari Abu Mas'ud Al-Badri radhiyallahu 'anhu: ketika ayat sedekah turun, kami menyewakan tenaga (jadi buruh) untuk bisa bersedekah. Datang seorang sahabat (Abu 'Aqil) bersedekah satu sha' kurma — separuh hasil kerjanya semalam. Datang sahabat lain bersedekah harta yang banyak. Munafik mengejek: 'Allah tidak butuh sedekah orang ini (yang sedikit), dan yang itu (yang banyak) tidak melakukannya kecuali untuk pamer.' Maka Allah menurunkan ayat ini mengecam mereka: '(Yaitu) orang-orang munafik yang mencela orang-orang mukmin yang memberi sedekah dengan sukarela dan mencela orang-orang yang tidak memperoleh selain sekedar kesanggupannya, sehingga mereka menghina mereka. Allah akan membalas penghinaan mereka...'",
			Source:  "HR. Bukhari No. 4668, 1415; HR. Muslim No. 1018; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Sedekah Menghapus Dosa (Lelaki yang Mencium Wanita)",
			Narrator: "Abdullah bin Mas'ud radhiyallahu 'anhu",
			SurahID:  11, AyahFrom: 114, AyahTo: 114,
			Content: "Diriwayatkan dari Abdullah bin Mas'ud radhiyallahu 'anhu: seseorang menemui Rasulullah shallallahu 'alaihi wa sallam dan berkata: 'Wahai Rasulullah, aku berinteraksi dengan seorang wanita di kebun di luar kota, lalu kucium dan kupeluk dia, namun aku tidak menjima'inya. Maka putuskanlah hukumnya atasku.' Umar berkata: 'Sungguh Allah telah menutupimu seandainya engkau menutupinya sendiri (tidak mengaku).' Lalu lelaki itu pergi. Rasulullah memanggilnya kembali, dan turunlah ayat: 'Dirikanlah shalat itu pada kedua tepi siang dan pada bagian permulaan daripada malam. Sesungguhnya kebajikan-kebajikan itu menghapus dosa-dosa.' Lelaki bertanya: 'Apakah ini khusus untukku?' Rasulullah menjawab: 'Untuk seluruh umatku.'",
			Source:  "HR. Bukhari No. 526, 4687; HR. Muslim No. 2763; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Ammar bin Yasir & Taqiyyah di Bawah Penyiksaan",
			Narrator: "Ammar bin Yasir radhiyallahu 'anhu",
			SurahID:  16, AyahFrom: 106, AyahTo: 106,
			Content: "Diriwayatkan: kaum musyrikin Quraisy menyiksa Ammar bin Yasir radhiyallahu 'anhu dengan siksaan yang amat berat sampai dia terpaksa mengucapkan kekufuran (sambil hatinya tetap iman). Ammar datang menangis kepada Rasulullah shallallahu 'alaihi wa sallam. Beliau bertanya: 'Bagaimana keadaan hatimu?' Ammar menjawab: 'Tetap tenteram dengan iman.' Rasulullah bersabda: 'Jika mereka kembali (memaksa), maka kembalilah (mengucap demikian).' Maka Allah menurunkan: '...kecuali orang yang dipaksa kafir padahal hatinya tetap tenang dalam keimanan...' (penghasilan rukhshah taqiyyah dalam keadaan terpaksa). Adapun ayah-bunda Ammar (Yasir dan Sumayyah) gugur sebagai syuhada pertama dalam Islam karena menolak murtad.",
			Source:  "HR. Hakim 2/389 (shahih sesuai syarat Bukhari-Muslim); HR. Baihaqi; Shahih oleh Al-Albani; Tafsir Ibnu Katsir 4/605",
		},
		{
			Title:    "Mutslah Hamzah & Larangan Membalas Berlebihan",
			Narrator: "Ubay bin Ka'b radhiyallahu 'anhu",
			SurahID:  16, AyahFrom: 126, AyahTo: 128,
			Content: "Diriwayatkan dari Ubay bin Ka'b radhiyallahu 'anhu: ketika Hamzah radhiyallahu 'anhu (paman Nabi) gugur di Uhud dan jasadnya di-mutslah (dirobek perutnya, hatinya dikeluarkan, hidung dan telinga dipotong) oleh Hindun, Rasulullah shallallahu 'alaihi wa sallam berjanji: 'Jika Allah memberiku kemenangan atas mereka, sungguh aku akan mutslah tujuh puluh dari mereka.' Maka Allah menurunkan ayat: 'Jika kalian membalas, maka balaslah dengan setara dengan yang ditimpakan kepada kalian. Tetapi jika kalian bersabar, sungguh itu lebih baik bagi orang-orang yang sabar.' Rasulullah bersabar dan tidak melakukan mutslah, dan beliau membayar kafarat sumpah.",
			Source:  "HR. Tirmidzi No. 3129 (hasan); HR. Ahmad 5/135; HR. Hakim 2/358 (shahih); Shahih oleh Al-Albani",
		},
		{
			Title:    "Isra' Mi'raj — Awal Surat Al-Isra'",
			Narrator: "Anas bin Malik radhiyallahu 'anhu",
			SurahID:  17, AyahFrom: 1, AyahTo: 1,
			Content: "Diriwayatkan dari Anas bin Malik radhiyallahu 'anhu (dan Malik bin Sha'sha'ah, dan Abu Dzar): Rasulullah shallallahu 'alaihi wa sallam diisrakan dari Masjidil Haram (Mekah) ke Masjidil Aqsha (Baitul Maqdis) di malam hari di atas Buraq, ditemani Jibril 'alaihissalam. Dari sana beliau di-mi'raj-kan ke langit, melewati ketujuh langit, dan kembali ke Mekah dalam satu malam yang sama. Quraisy mengejek dan tidak percaya, namun beliau menjawab dengan menggambarkan kafilah dan ciri Baitul Maqdis. Allah menurunkan ayat awal Al-Isra' sebagai bukti perjalanan ini.",
			Source:  "HR. Bukhari No. 3887, 7517; HR. Muslim No. 162, 164; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Jibril Datang Lambat (Kalau Tuhanmu Tidak Lupa)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  19, AyahFrom: 64, AyahTo: 64,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: Rasulullah shallallahu 'alaihi wa sallam berkata kepada Jibril 'alaihissalam: 'Apa yang menghalangimu mengunjungi kami lebih sering dari yang sudah-sudah?' Maka turunlah ayat ini sebagai jawaban Jibril: 'Dan tidaklah kami (para malaikat) turun, melainkan dengan perintah Tuhanmu. Milik-Nyalah apa-apa yang ada di hadapan kita, di belakang kita, dan apa-apa yang ada di antara keduanya. Dan tidaklah Tuhanmu lupa.' Penegasan bahwa kedatangan wahyu adalah dengan izin Allah, bukan inisiatif Jibril sendiri.",
			Source:  "HR. Bukhari No. 4731, 3218; Shahih",
		},
		{
			Title:    "Izin Berperang Pertama Kali (Setelah Hijrah)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  22, AyahFrom: 39, AyahTo: 40,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: ketika Rasulullah shallallahu 'alaihi wa sallam diusir dari Mekah, Abu Bakar berkata: 'Mereka mengusir Nabi mereka, sungguh mereka akan binasa.' Lalu Allah menurunkan: 'Telah diizinkan (berperang) bagi orang-orang yang diperangi, karena mereka dizalimi. Dan sungguh Allah Maha Kuasa menolong mereka. (Yaitu) orang-orang yang diusir dari kampung halaman tanpa alasan yang benar, kecuali karena mereka berkata: Tuhan kami adalah Allah.' Inilah ayat pertama yang mengizinkan jihad qital, setelah sekian lama umat Islam diperintahkan bersabar di Mekah.",
			Source:  "HR. Tirmidzi No. 3171 (hasan); HR. An-Nasa'i No. 3085; HR. Ahmad 1/216; Shahih oleh Al-Albani; Tafsir Ibnu Katsir 5/438",
		},
		{
			Title:    "Tobat Wahsyi (Sang Pembunuh Hamzah)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  25, AyahFrom: 68, AyahTo: 70,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: Wahsyi (yang membunuh Hamzah di Uhud) mengirim surat kepada Rasulullah shallallahu 'alaihi wa sallam menanyakan apakah masih ada tobat untuknya, sebab dia telah membunuh, berzina, dan menyekutukan Allah. Maka Allah menurunkan ayat ini (Al-Furqan: 68-70): yang merangkum tiga dosa besar (syirik, membunuh, zina) lalu menyebut 'kecuali orang yang bertobat, beriman, dan beramal shalih. Mereka itu Allah akan mengganti kejahatan mereka dengan kebaikan.' Wahsyi pun masuk Islam, dan kelak ikut perang Yamamah membunuh Musailamah Al-Kadzdzab dengan tombak yang sama yang digunakan untuk membunuh Hamzah. Beliau berkata: 'Aku membunuh sebaik-baik manusia di masa jahiliahku, dan seburuk-buruk manusia di masa Islamku.'",
			Source:  "HR. Bukhari No. 4810 (Wahsyi membunuh Musailamah); HR. Bukhari No. 3844 (sebab nuzul); HR. Muslim No. 122; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Engkau Tidak Bisa Memberi Hidayah Kepada Yang Engkau Cintai (Abu Thalib)",
			Narrator: "Abu Hurairah / Sa'id bin Al-Musayyab radhiyallahu 'anhuma",
			SurahID:  28, AyahFrom: 56, AyahTo: 56,
			Content: "Diriwayatkan dari Sa'id bin Al-Musayyab dari ayahnya: ketika Abu Thalib (paman Rasulullah) menjelang wafat dalam keadaan masih kafir meskipun Rasulullah shallallahu 'alaihi wa sallam berusaha memintanya mengucap syahadat, Allah menurunkan ayat: 'Sesungguhnya engkau (Muhammad) tidak akan dapat memberi petunjuk kepada orang yang engkau kasihi, tetapi Allah memberi petunjuk kepada orang yang Dia kehendaki.' Hidayah taufiq adalah hak prerogatif Allah; tugas Rasul hanya menyampaikan dan berdoa.",
			Source:  "HR. Bukhari No. 4772, 1360; HR. Muslim No. 24-25; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Ibu Sa'd bin Abi Waqqash Memboikot Makan",
			Narrator: "Sa'd bin Abi Waqqash radhiyallahu 'anhu",
			SurahID:  29, AyahFrom: 8, AyahTo: 8,
			Content: "Diriwayatkan dari Sa'd bin Abi Waqqash radhiyallahu 'anhu: ketika aku masuk Islam, ibuku bersumpah tidak akan makan dan minum sampai aku murtad. Hari pertama kuabaikan, hari kedua, hari ketiga dia mulai jatuh pingsan karena lapar. Aku berkata: 'Demi Allah, wahai ibu, andai engkau punya seratus nyawa lalu satu per satu lepas dariku, tetap aku tidak akan meninggalkan agamaku ini, walau bagaimanapun. Maka makanlah jika engkau mau, atau jangan makan.' Maka ibuku makan. Allah menurunkan ayat ini: 'Kami wajibkan manusia berbuat baik kepada kedua orang tuanya. Tapi jika keduanya memaksamu mempersekutukan-Ku dengan apa yang engkau tidak punya pengetahuan, maka jangan engkau taati keduanya...'",
			Source:  "HR. Muslim No. 1748; HR. Tirmidzi No. 3079 (hasan shahih); HR. Ahmad 1/181; Shahih",
		},
		{
			Title:    "Kemenangan Romawi atas Persia (Taruhan Abu Bakar)",
			Narrator: "Niyar bin Mukram Al-Aslami radhiyallahu 'anhu",
			SurahID:  30, AyahFrom: 1, AyahTo: 5,
			Content: "Diriwayatkan: ketika Persia mengalahkan Romawi (Bizantium) sebelum Hijrah, kaum musyrikin Quraisy bersuka cita karena Persia adalah penyembah api (mirip mereka — tidak punya kitab samawi), sedangkan Romawi adalah Ahli Kitab seperti Muslim. Allah menurunkan: 'Bangsa Romawi telah dikalahkan, di negeri yang terdekat. Tapi setelah kekalahannya itu mereka akan menang dalam beberapa tahun (3-9 tahun).' Abu Bakar mendengar Quraisy mengejek prediksi ini. Beliau bertaruh dengan Ubay bin Khalaf (riwayat lain: dengan beberapa orang) tentang kemenangan Romawi. Setelah ayat turun, Abu Bakar memperpanjang taruhan. Romawi akhirnya menang di tahun ke-7 H sesuai prediksi, dan Abu Bakar menerima taruhan (sebelum riba diharamkan).",
			Source:  "HR. Tirmidzi No. 3193-3194 (hasan); HR. Ahmad 1/304; HR. Hakim 2/410 (shahih); Shahih oleh Al-Albani",
		},
		{
			Title:    "Wahai Hamba-Ku yang Melampaui Batas (Pembunuh 99 Jiwa)",
			Narrator: "Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  39, AyahFrom: 53, AyahTo: 53,
			Content: "Diriwayatkan dari Ibnu Abbas radhiyallahu 'anhuma: ada beberapa orang dari musyrikin Mekah yang banyak membunuh dan banyak berzina. Mereka datang kepada Rasulullah shallallahu 'alaihi wa sallam dan bertanya: 'Sungguh apa yang engkau ucapkan dan dakwahkan baik. Tapi beritahu kami, apakah dosa-dosa kami yang besar masih ada penghapusnya?' Maka Allah menurunkan: 'Katakanlah: Wahai hamba-Ku yang melampaui batas terhadap diri sendiri, janganlah kalian putus asa dari rahmat Allah. Sesungguhnya Allah mengampuni dosa-dosa semuanya. Sungguh Dia Maha Pengampun lagi Maha Penyayang.' Riwayat lain dari Bukhari/Muslim tentang seorang Bani Israil yang membunuh 99 orang lalu mencari ulama untuk tobat — pesan tentang luasnya rahmat Allah.",
			Source:  "HR. Bukhari No. 4810; HR. Muslim No. 122; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Birrul Walidain & Sa'd bin Abi Waqqash (Paralel di Al-Ahqaf)",
			Narrator: "Sa'd bin Abi Waqqash radhiyallahu 'anhu",
			SurahID:  46, AyahFrom: 15, AyahTo: 15,
			Content: "Diriwayatkan: ayat ini turun berkenaan dengan Sa'd bin Abi Waqqash radhiyallahu 'anhu. Konteks paralel dengan QS. Al-'Ankabut: 8 — saat ibunya memboikot makan agar Sa'd murtad, dan Sa'd tetap teguh pada Islam, Allah menurunkan ayat ini menyandingkan: kewajiban berbuat ihsan (kebaikan) kepada orang tua tetap berlaku, namun bila mereka memaksa syirik maka taat kepada Allah didahulukan. Riwayat ini juga ditafsirkan secara umum sebagai pedoman birrul walidain bagi kaum muslimin.",
			Source:  "HR. Muslim No. 1748; HR. Tirmidzi No. 3079; Tafsir Ibnu Katsir 7/279; Shahih",
		},
		{
			Title:    "Yang Tidak Diam Saat Mendengar Al-Qur'an (Adab Mendengar)",
			Narrator: "Abu Hurairah radhiyallahu 'anhu",
			SurahID:  7, AyahFrom: 204, AyahTo: 204,
			Content: "Diriwayatkan: dahulu di awal Madinah, sebagian sahabat berbicara dalam shalat dengan saudaranya tentang urusan biasa, atau menjawab salam saat shalat. Bahkan dalam riwayat lain: kaum muslimin masih berbicara saat imam membaca Al-Qur'an di shalat berjamaah. Maka Allah menurunkan ayat: 'Apabila dibacakan Al-Qur'an, maka dengarkanlah dengan baik dan diamlah, agar kalian mendapat rahmat.' Ayat ini menjadi dalil wajibnya makmum diam dan menyimak saat imam membaca dalam shalat jahriyyah, dan adab menyimak Al-Qur'an di luar shalat.",
			Source:  "HR. Muslim No. 404; HR. Abu Dawud No. 824; Shahih; Tafsir Ibnu Katsir 3/535",
		},
		{
			Title:    "Larangan Memuji Diri Sendiri (Tazkiyatun Nafs)",
			Narrator: "Zainab binti Abi Salamah radhiyallahu 'anha",
			SurahID:  53, AyahFrom: 32, AyahTo: 32,
			Content: "Diriwayatkan dari Zainab binti Abi Salamah radhiyallahu 'anha: aku dinamai Barrah (artinya: yang baik dan suci), lalu Rasulullah shallallahu 'alaihi wa sallam mengganti namaku menjadi Zainab. Beliau bersabda: 'Janganlah kalian memuji diri sendiri (mensucikan diri), Allah lebih tahu siapa yang baik di antara kalian.' Sebagai pengamalan ayat: 'Janganlah kalian mensucikan diri kalian; Dia (Allah) lebih tahu siapa yang bertakwa.' Riwayat ini menjadi adab tasmiyah dan larangan tazkiyah diri.",
			Source:  "HR. Bukhari No. 6192; HR. Muslim No. 2142; Shahih (Muttafaq 'alaih)",
		},
		{
			Title:    "Doa Suami-Istri Saat Berlepas Diri di Akhirat",
			Narrator: "Tafsir, Ibnu Abbas radhiyallahu 'anhuma",
			SurahID:  43, AyahFrom: 67, AyahTo: 67,
			Content: "Diriwayatkan: ayat 'Teman-teman akrab pada hari itu sebagiannya menjadi musuh bagi yang lain, kecuali orang-orang yang bertakwa' turun untuk memperingatkan tentang persahabatan jahat. Konteks: 'Uqbah bin Abi Mu'aith (musyrik Quraisy) tadinya bersahabat dengan Umayyah bin Khalaf, lalu hampir masuk Islam karena pengaruh Rasulullah. Umayyah memarahinya dan menghasut sampai 'Uqbah meludahi Rasulullah dan kembali kafir. Akhirnya 'Uqbah dieksekusi setelah Badar. Allah menurunkan ayat ini sebagai pelajaran bahwa sahabat duniawi yang membawa pada kesesatan akan jadi musuh di akhirat — kecuali persahabatan yang dijalin di atas takwa.",
			Source:  "Tafsir Ibnu Katsir 7/233 (riwayat dari Ali bin Abi Thalhah dari Ibnu Abbas, jalur shahih); HR. Hakim 2/444; Lubabun Nuqul",
		},
	}
}
