import {
    BsBarChart,
    BsBell,
    BsBook,
    BsCalendar3,
    BsJournalCheck,
    BsStickyFill,
    BsTrophyFill,
} from 'react-icons/bs';
import { FaBrain, FaQuran } from 'react-icons/fa';
import { GiCompass, GiOpenBook } from 'react-icons/gi';
import { ImBook } from 'react-icons/im';
import {
    MdAccessTime,
    MdArticle,
    MdCalendarMonth,
    MdCheckBox,
    MdFlag,
    MdFormatListBulleted,
    MdMenuBook,
    MdMosque,
    MdOutlineAutoStories,
    MdOutlineContactPhone,
    MdOutlineDirectionsWalk,
    MdOutlinePlayLesson,
    MdRefresh,
    MdSelfImprovement,
    MdStar,
    MdTimeline,
} from 'react-icons/md';
import { TbApi } from 'react-icons/tb';

export const linksMenu = [
    { label: 'Quran', href: '/quran', icon: <FaQuran /> },
    { label: 'Hadith', href: '/hadith', icon: <ImBook /> },
    { label: 'Dev', href: '/dev', icon: <TbApi /> },
    { label: 'Contact', href: '/contact', icon: <MdOutlineContactPhone /> },
];

export const linksMenuContent = [
    { label: 'Asmaul Husna', href: '/asmaul-husna', icon: <MdStar /> },
    { label: 'Doa', href: '/doa', icon: <MdSelfImprovement /> },
    { label: 'Dzikir', href: '/dzikir', icon: <GiOpenBook /> },
    { label: 'Wirid Sunnah', href: '/wirid', icon: <GiOpenBook /> },
    { label: 'Tahlil & Yasin', href: '/tahlil', icon: <BsBook /> },
    { label: 'Siroh', href: '/siroh', icon: <MdMenuBook /> },
    { label: 'Blog', href: '/blog', icon: <MdArticle /> },
    { label: 'Kajian Islam', href: '/kajian', icon: <MdOutlinePlayLesson /> },
    { label: 'Asbabun Nuzul', href: '/asbabun-nuzul', icon: <MdMenuBook /> },
    { label: 'Tafsir Al-Quran', href: '/tafsir', icon: <MdOutlineAutoStories /> },
    { label: 'Fiqh Ringkas', href: '/fiqh', icon: <MdOutlineAutoStories /> },
    { label: 'Kamus Arab', href: '/kamus', icon: <BsBook /> },
    { label: 'Kalender Hijriah', href: '/hijri', icon: <MdCalendarMonth /> },
    { label: 'Jadwal Sholat', href: '/jadwal-sholat', icon: <MdAccessTime /> },
    { label: 'Leaderboard', href: '/leaderboard', icon: <BsTrophyFill /> },
    { label: 'Quiz Islami', href: '/quiz', icon: <FaBrain /> },
    { label: 'Sejarah Islam', href: '/sejarah', icon: <MdTimeline /> },
    { label: 'Manasik Haji & Umrah', href: '/manasik', icon: <MdOutlineDirectionsWalk /> },
    { label: 'Arah Kiblat', href: '/kiblat', icon: <GiCompass /> },
    { label: 'Imsakiyah', href: '/imsakiyah', icon: <BsCalendar3 /> },
];

export const linksMenuAuth = [
    { label: 'Dashboard', href: '/dashboard', icon: <BsBarChart /> },
    { label: 'Bookmark', href: '/bookmarks' },
    { label: 'Hafalan', href: '/hafalan' },
    { label: "Muroja'ah", href: '/muroja-ah', icon: <MdRefresh /> },
    { label: 'Tilawah', href: '/tilawah', icon: <BsJournalCheck /> },
    { label: 'Amalan', href: '/amalan', icon: <MdFormatListBulleted /> },
    { label: 'Sholat Tracker', href: '/sholat-tracker', icon: <MdMosque /> },
    { label: 'Catatan', href: '/notes', icon: <BsStickyFill /> },
    { label: 'Muhasabah', href: '/muhasabah', icon: <MdSelfImprovement /> },
    { label: 'Target Belajar', href: '/goals', icon: <MdFlag /> },
    { label: 'Notifikasi', href: '/notifications', icon: <BsBell /> },
    { label: 'Profil', href: '/profile' },
];

export const listMasjidImage = [
	{
		label: 'Masjid Al-Haram',
		src: '/assets/images/masjid/Haram1.jpg',
		alt: 'Masjid Al-Haram',
	},
	{
		label: 'Masjid Al-Haram',
		src: '/assets/images/masjid/Haram2.jpg',
		alt: 'Masjid Al-Haram',
	},
	{
		label: 'Masjid Al-Haram',
		src: '/assets/images/masjid/Haram3.jpg',
		alt: 'Masjid Al-Haram',
	},
	{
		label: 'Masjid Al-Haram',
		src: '/assets/images/masjid/Haram4.jpg',
		alt: 'Masjid Al-Haram',
	},
	{ label: 'Masjid', src: '/assets/images/masjid/Masjid.jpg', alt: 'Masjid' },
	{ label: 'Masjid', src: '/assets/images/masjid/Masjid1.jpg', alt: 'Masjid' },
	{ label: 'Masjid', src: '/assets/images/masjid/Masjid2.jpg', alt: 'Masjid' },
	{ label: 'Masjid', src: '/assets/images/masjid/Masjid3.jpg', alt: 'Masjid' },
	{ label: 'Masjid', src: '/assets/images/masjid/Masjid4.jpg', alt: 'Masjid' },
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi.jpg',
		alt: 'Masjid Nabawi',
	},
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi1.jpg',
		alt: 'Masjid Nabawi',
	},
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi2.jpg',
		alt: 'Masjid Nabawi',
	},
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi3.jpg',
		alt: 'Masjid Nabawi',
	},
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi4.jpg',
		alt: 'Masjid Nabawi',
	},
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi5.jpg',
		alt: 'Masjid Nabawi',
	},
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi6.jpg',
		alt: 'Masjid Nabawi',
	},
	// { label: 'Masjid Nabawi', src: '/assets/images/masjid/Nabawi7.jpg', alt:'Masjid Nabawi' },
];

export const hadithTabList = [
	{
		label: 'Book',
		alt: 'Book',
		href: '#book',
	},
	{
		label: 'Theme',
		alt: 'Theme',
		href: '#theme',
	},
	{
		label: 'Chapter',
		alt: 'Chapter',
		href: '#chapter',
	},
	{
		label: 'Hadith',
		alt: 'Hadith',
		href: '#hadith',
	},
];

export const listKitabHadith = [
	{
		id: 1,
		label: 'Shahih Bukhari',
		slug: 'bukhari',
		src: '/assets/images/kitab/hadith/bukhari.png',
		alt: 'Shahih Bukhari',
		href: '/hadith/bukhari',
	},
	{
		id: 2,
		label: 'Shahih Muslim',
		slug: 'muslim',
		src: '/assets/images/kitab/hadith/muslim.png',
		alt: 'Shahih Muslim',
		href: '/hadith/muslim',
	},
	{
		id: 3,
		label: 'Sunan Abu Daud',
		slug: 'abudaud',
		src: '/assets/images/kitab/hadith/abudaud.png',
		alt: 'Sunan Abu Daud',
		href: '/hadith/abudaud',
	},
	{
		id: 4,
		label: 'Sunan Tirmidzi',
		slug: 'tirmidzi',
		src: '/assets/images/kitab/hadith/abudaud.png',
		alt: 'Sunan Tirmidzi',
		href: '/hadith/tirmidzi',
	},
	{
		id: 5,
		label: `Sunan Nasa'i`,
		slug: 'nasai',
		src: '/assets/images/kitab/hadith/nasai.png',
		alt: `Sunan Nasa'i`,
		href: `/hadith/nasa'i`,
	},
	{
		id: 6,
		label: 'Sunan Ibnu Majah',
		slug: 'ibnumajah',
		src: '/assets/images/kitab/hadith/ibnumajah.png',
		alt: 'Sunan Ibnu Majah',
		href: '/hadith/ibnumajah',
	},
	{
		id: 7,
		label: `Muwatha' Malik`,
		slug: 'malik',
		src: '/assets/images/kitab/hadith/malik.png',
		alt: `Muwatha' Malik`,
		href: '/hadith/malik',
	},
	{
		id: 8,
		label: 'Musnan Ahmad',
		slug: 'ahmad',
		src: '/assets/images/kitab/hadith/ahmad.png',
		alt: 'Musnan Ahmad',
		href: '/hadith/ahmad',
	},
	{
		id: 9,
		label: 'Sunan Darimi',
		slug: 'darimi',
		src: '/assets/images/kitab/hadith/darimi.png',
		alt: 'Sunan Darimi',
		href: '/hadith/darimi',
	},
];

export const listTajweed = [
    {
        Type: 'hamza-wasl',
        Identifier: '[h',
        Colour: '#AAAAAA',
        CSS: 'ham_wasl',
        Arabic: 'هَمْزَةُ الْوَصْل',
        Description: 'Hamzat ul Wasl',
        DescriptionId: 'Hamzah penyambung — tidak dibaca di tengah kalimat',
        DescriptionEn: 'Connecting Hamzah — not pronounced in the middle of speech',
    },
    {
        Type: 'silent',
        Identifier: '[s',
        Colour: '#AAAAAA',
        CSS: 'slnt',
        Arabic: 'حَرْفٌ سَاكِن',
        Description: 'Silent',
        DescriptionId: 'Huruf yang dimatikan (sukun), tidak berbunyi',
        DescriptionEn: 'Letter with sukun (sukoon) — not pronounced',
    },
    {
        Type: 'laam-shamsiyah',
        Identifier: '[l',
        Colour: '#AAAAAA',
        CSS: 'slnt',
        Arabic: 'لَامٌ شَمْسِيَّة',
        Description: 'Lam Shamsiyyah',
        DescriptionId: 'Lam diidghamkan ke huruf syamsiyah yang mengikutinya',
        DescriptionEn: 'Lam assimilated into the following shamsiyyah letter',
    },
    {
        Type: 'madda-normal',
        Identifier: '[n',
        Colour: '#537FFF',
        CSS: 'madda_normal',
        Arabic: 'مَدٌّ طَبِيعِيّ',
        Description: 'Normal Prolongation: 2 Vowels',
        DescriptionId: 'Mad asli / alami — dibaca 2 harakat',
        DescriptionEn: 'Natural madd — read 2 harakats',
    },
    {
        Type: 'madda-permissible',
        Identifier: '[p',
        Colour: '#4050FF',
        CSS: 'madda_permissible',
        Arabic: 'مَدٌّ جَائِز',
        Description: 'Permissible Prolongation: 2, 4, 6 Vowels',
        DescriptionId: 'Mad boleh — dibaca 2, 4, atau 6 harakat (ikhtiyar)',
        DescriptionEn: 'Optional madd — read 2, 4, or 6 harakats (ikhtiyar)',
    },
    {
        Type: 'madda-necesssary',
        Identifier: '[m',
        Colour: '#000EBC',
        CSS: 'madda_necessary',
        Arabic: 'مَدٌّ لَازِم',
        Description: 'Necessary Prolongation: 6 Vowels',
        DescriptionId: 'Mad wajib — harus dibaca 6 harakat',
        DescriptionEn: 'Obligatory madd — must be read 6 harakats',
    },
    {
        Type: 'qalaqah',
        Identifier: '[q',
        Colour: '#DD0008',
        CSS: 'qlq',
        Arabic: 'قَلْقَلَة',
        Description: 'Qalaqah',
        DescriptionId: 'Bunyi memantul pada huruf ق ط ب ج د saat mati/waqaf',
        DescriptionEn: 'Echoing sound on letters ق ط ب ج د when stopped/paused',
    },
    {
        Type: 'madda-obligatory',
        Identifier: '[o',
        Colour: '#2144C1',
        CSS: 'madda_pbligatory',
        Arabic: 'مَدٌّ وَاجِب',
        Description: 'Obligatory Prolongation: 4-5 Vowels',
        DescriptionId: 'Mad wajib muttasil — dibaca 4-5 harakat',
        DescriptionEn: 'Mad wajib muttasil — read 4-5 harakats',
    },
    {
        Type: 'ikhafa-shafawi',
        Identifier: '[c',
        Colour: '#D500B7',
        CSS: 'ikhf_shfw',
        Arabic: 'إِخْفَاءٌ شَفَوِيّ',
        Description: "Ikhafa' Shafawi - With Meem",
        DescriptionId: "Mim sukun bertemu ba' — dibaca samar dengan dengung",
        DescriptionEn: "Meem sukun meets ba' — read softly with nasalization",
    },
    {
        Type: 'ikhafa',
        Identifier: '[f',
        Colour: '#9400A8',
        CSS: 'ikhf',
        Arabic: 'إِخْفَاء',
        Description: "Ikhafa'",
        DescriptionId: 'Nun sukun/tanwin bertemu 15 huruf ikhfa — dibaca samar',
        DescriptionEn: 'Noon sukun/tanween meets one of 15 ikhfa letters — read softly',
    },
    {
        Type: 'idgham-shafawi',
        Identifier: '[w',
        Colour: '#58B800',
        CSS: 'idghm_shfw',
        Arabic: 'إِدْغَامٌ شَفَوِيّ',
        Description: 'Idgham Shafawi - With Meem',
        DescriptionId: 'Mim sukun bertemu mim — dilebur dengan dengung',
        DescriptionEn: 'Meem sukun meets meem — merged with nasalization',
    },
    {
        Type: 'iqlab',
        Identifier: '[i',
        Colour: '#26BFFD',
        CSS: 'iqlb',
        Arabic: 'إِقْلَاب',
        Description: 'Iqlab',
        DescriptionId: "Nun sukun/tanwin bertemu ba' — berubah bunyi menjadi mim",
        DescriptionEn: "Noon sukun/tanween meets ba' — sound changes to meem",
    },
    {
        Type: 'idgham-with-ghunnah',
        Identifier: '[a',
        Colour: '#169777',
        CSS: 'idgh_ghn',
        Arabic: 'إِدْغَامٌ بِغُنَّة',
        Description: 'Idgham - With Ghunnah',
        DescriptionId: 'Nun sukun/tanwin masuk ke ي ن م و — dengan dengung',
        DescriptionEn: 'Noon sukun/tanween enters ي ن م و — with nasalization',
    },
    {
        Type: 'idgham-without-ghunnah',
        Identifier: '[u',
        Colour: '#169200',
        CSS: 'idgh_w_ghn',
        Arabic: 'إِدْغَامٌ بِلَا غُنَّة',
        Description: 'Idgham - Without Ghunnah',
        DescriptionId: 'Nun sukun/tanwin masuk ke ل ر — tanpa dengung',
        DescriptionEn: 'Noon sukun/tanween enters ل ر — without nasalization',
    },
    {
        Type: 'idgham-mutajanisayn',
        Identifier: '[d',
        Colour: '#A1A1A1',
        CSS: 'idgh_mus',
        Arabic: 'إِدْغَامُ الْمُتَجَانِسَيْن',
        Description: 'Idgham - Mutajanisayn',
        DescriptionId: 'Dua huruf sejenis makhraj & sifat bertemu — dilebur',
        DescriptionEn: 'Two letters of identical makhraj & sifat meet — merged',
    },
    {
        Type: 'idgham-mutaqaribayn',
        Identifier: '[b',
        Colour: '#A1A1A1',
        CSS: 'idgh_mus',
        Arabic: 'إِدْغَامُ الْمُتَقَارِبَيْن',
        Description: 'Idgham - Mutaqaribayn',
        DescriptionId: 'Dua huruf berdekatan makhrajnya bertemu — dilebur',
        DescriptionEn: 'Two letters with close makhraj meet — merged',
    },
    {
        Type: 'ghunnah',
        Identifier: '[g',
        Colour: '#FF7E1E',
        CSS: 'ghn',
        Arabic: 'غُنَّة',
        Description: 'Ghunnah: 2 Vowels',
        DescriptionId: 'Dengung 2 harakat pada nun/mim bertasydid ( نّ / مّ )',
        DescriptionEn: 'Nasalization of 2 harakats on shadda noon/meem ( نّ / مّ )',
    },
];
